-- FinanceSys Eastmoney simulation trading ledger.
-- Apply to expert_trade_test first, verify, then apply unchanged to expert_trade.

CREATE TABLE IF NOT EXISTS `trading_agent_runs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_key` char(64) NOT NULL,
  `trigger_type` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'QUEUED',
  `decision_provider` varchar(32) NOT NULL,
  `strategy_name` varchar(128) NOT NULL,
  `strategy_version` varchar(64) NOT NULL,
  `schema_version` varchar(64) NOT NULL,
  `prompt_version` varchar(64) NOT NULL DEFAULT '',
  `tool_contract_version` varchar(64) NOT NULL,
  `as_of_time` timestamp(3) NOT NULL,
  `input_cursor` varchar(255) NOT NULL DEFAULT '',
  `input_snapshot_hash` char(64) NOT NULL,
  `request_json` json NOT NULL,
  `raw_output_json` json NOT NULL,
  `candidate_count` int NOT NULL DEFAULT 0,
  `intent_count` int NOT NULL DEFAULT 0,
  `rejected_output_count` int NOT NULL DEFAULT 0,
  `dry_run` tinyint(1) NOT NULL DEFAULT 0,
  `worker_id` varchar(128) NOT NULL DEFAULT '',
  `queued_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` timestamp(3) NULL DEFAULT NULL,
  `finished_at` timestamp(3) NULL DEFAULT NULL,
  `error_code` varchar(64) NOT NULL DEFAULT '',
  `error_message` text NOT NULL,
  `config_version` bigint NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_agent_runs_key` (`run_key`),
  KEY `idx_trading_agent_runs_status` (`status`,`queued_at`),
  KEY `idx_trading_agent_runs_strategy` (`strategy_name`,`as_of_time`),
  KEY `idx_trading_agent_runs_trigger` (`trigger_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_intents` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trading_agent_run_id` bigint NOT NULL,
  `intent_key` char(64) NOT NULL,
  `recommendation_event_id` bigint NULL DEFAULT NULL,
  `candidate_plan_id` bigint NULL DEFAULT NULL,
  `symbol` varchar(32) NOT NULL,
  `market` varchar(16) NOT NULL,
  `asset_type` varchar(32) NOT NULL,
  `eastmoney_symbol` varchar(32) NOT NULL DEFAULT '',
  `trade_action` varchar(16) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'PROPOSED',
  `proposed_order_type` varchar(16) NOT NULL DEFAULT 'LIMIT',
  `proposed_limit_price` decimal(20,6) NULL DEFAULT NULL,
  `proposed_position_ratio` decimal(18,8) NULL DEFAULT NULL,
  `proposed_volume` bigint NULL DEFAULT NULL,
  `confidence` decimal(18,8) NOT NULL DEFAULT 0,
  `valid_from` timestamp(3) NOT NULL,
  `valid_until` timestamp(3) NOT NULL,
  `reason` text NOT NULL,
  `evidence_refs_json` json NOT NULL,
  `raw_intent_json` json NOT NULL,
  `rejection_code` varchar(64) NOT NULL DEFAULT '',
  `rejection_message` text NOT NULL,
  `strategy_version` varchar(64) NOT NULL,
  `config_version` bigint NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_intents_key` (`intent_key`),
  KEY `idx_trading_intents_run` (`trading_agent_run_id`,`id`),
  KEY `idx_trading_intents_event` (`recommendation_event_id`),
  KEY `idx_trading_intents_plan` (`candidate_plan_id`),
  KEY `idx_trading_intents_symbol` (`symbol`,`created_at`),
  KEY `idx_trading_intents_status` (`status`,`valid_until`),
  CONSTRAINT `fk_trading_intents_run` FOREIGN KEY (`trading_agent_run_id`) REFERENCES `trading_agent_runs` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_trading_intents_event` FOREIGN KEY (`recommendation_event_id`) REFERENCES `recommendation_events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_trading_intents_plan` FOREIGN KEY (`candidate_plan_id`) REFERENCES `trade_candidate_plans` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_risk_checks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trading_intent_id` bigint NOT NULL,
  `evaluation_no` int NOT NULL DEFAULT 1,
  `check_code` varchar(64) NOT NULL,
  `check_order` int NOT NULL,
  `passed` tinyint(1) NOT NULL,
  `decision` varchar(32) NOT NULL,
  `reason_message` text NOT NULL,
  `observed_json` json NOT NULL,
  `limit_json` json NOT NULL,
  `risk_version` varchar(64) NOT NULL,
  `config_version` bigint NOT NULL,
  `checked_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_risk_check` (`trading_intent_id`,`evaluation_no`,`check_code`),
  KEY `idx_trading_risk_checks_result` (`passed`,`check_code`,`checked_at`),
  CONSTRAINT `fk_trading_risk_checks_intent` FOREIGN KEY (`trading_intent_id`) REFERENCES `trading_intents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_orders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trading_intent_id` bigint NOT NULL,
  `client_order_id` varchar(64) NOT NULL,
  `idempotency_key` char(64) NOT NULL,
  `dispatch_seq` int NOT NULL DEFAULT 1,
  `environment` varchar(16) NOT NULL DEFAULT 'SIMULATION',
  `provider` varchar(32) NOT NULL DEFAULT 'EASTMONEY_GM',
  `account_id` varchar(128) NOT NULL,
  `strategy_id` varchar(128) NOT NULL,
  `symbol` varchar(32) NOT NULL,
  `eastmoney_symbol` varchar(32) NOT NULL,
  `side` varchar(16) NOT NULL,
  `position_effect` varchar(16) NOT NULL,
  `order_type` varchar(16) NOT NULL,
  `limit_price` decimal(20,6) NULL DEFAULT NULL,
  `volume` bigint NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DISPATCH_PENDING',
  `provider_status` varchar(32) NOT NULL DEFAULT '',
  `cl_ord_id` varchar(128) NULL DEFAULT NULL,
  `order_id` varchar(128) NULL DEFAULT NULL,
  `filled_volume` bigint NOT NULL DEFAULT 0,
  `filled_vwap` decimal(20,6) NULL DEFAULT NULL,
  `filled_amount` decimal(24,6) NOT NULL DEFAULT 0,
  `filled_commission` decimal(20,6) NOT NULL DEFAULT 0,
  `valid_until` timestamp(3) NOT NULL,
  `risk_snapshot_hash` char(64) NOT NULL,
  `dispatch_attempt_count` int NOT NULL DEFAULT 0,
  `next_dispatch_at` timestamp(3) NULL DEFAULT NULL,
  `submitted_at` timestamp(3) NULL DEFAULT NULL,
  `last_event_at` timestamp(3) NULL DEFAULT NULL,
  `finished_at` timestamp(3) NULL DEFAULT NULL,
  `error_code` varchar(64) NOT NULL DEFAULT '',
  `error_message` text NOT NULL,
  `request_json` json NOT NULL,
  `latest_provider_payload_json` json NOT NULL,
  `risk_version` varchar(64) NOT NULL,
  `config_version` bigint NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_orders_client` (`client_order_id`),
  UNIQUE KEY `uk_trading_orders_idempotency` (`idempotency_key`),
  UNIQUE KEY `uk_trading_orders_provider_cl_ord` (`provider`,`account_id`,`cl_ord_id`),
  KEY `idx_trading_orders_intent` (`trading_intent_id`,`dispatch_seq`),
  KEY `idx_trading_orders_status` (`status`,`next_dispatch_at`),
  KEY `idx_trading_orders_symbol` (`symbol`,`created_at`),
  KEY `idx_trading_orders_account` (`account_id`,`created_at`),
  CONSTRAINT `fk_trading_orders_intent` FOREIGN KEY (`trading_intent_id`) REFERENCES `trading_intents` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_order_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trading_order_id` bigint NOT NULL,
  `event_hash` char(64) NOT NULL,
  `event_type` varchar(32) NOT NULL,
  `source` varchar(32) NOT NULL DEFAULT 'BRIDGE_CALLBACK',
  `account_id` varchar(128) NOT NULL,
  `cl_ord_id` varchar(128) NOT NULL DEFAULT '',
  `provider_status` varchar(32) NOT NULL DEFAULT '',
  `normalized_status` varchar(32) NOT NULL DEFAULT '',
  `filled_volume` bigint NOT NULL DEFAULT 0,
  `filled_vwap` decimal(20,6) NULL DEFAULT NULL,
  `event_at` timestamp(3) NOT NULL,
  `received_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `raw_payload_json` json NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_order_events_hash` (`event_hash`),
  KEY `idx_trading_order_events_order` (`trading_order_id`,`event_at`),
  KEY `idx_trading_order_events_cl_ord` (`account_id`,`cl_ord_id`,`event_at`),
  CONSTRAINT `fk_trading_order_events_order` FOREIGN KEY (`trading_order_id`) REFERENCES `trading_orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_fills` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trading_order_id` bigint NOT NULL,
  `account_id` varchar(128) NOT NULL,
  `exec_id` varchar(128) NOT NULL,
  `cl_ord_id` varchar(128) NOT NULL,
  `symbol` varchar(32) NOT NULL,
  `eastmoney_symbol` varchar(32) NOT NULL,
  `side` varchar(16) NOT NULL,
  `price` decimal(20,6) NOT NULL,
  `volume` bigint NOT NULL,
  `amount` decimal(24,6) NOT NULL,
  `commission` decimal(20,6) NOT NULL DEFAULT 0,
  `exec_type` varchar(32) NOT NULL DEFAULT '',
  `traded_at` timestamp(3) NOT NULL,
  `raw_payload_json` json NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_fills_exec` (`account_id`,`exec_id`),
  KEY `idx_trading_fills_order` (`trading_order_id`,`traded_at`),
  KEY `idx_trading_fills_symbol` (`symbol`,`traded_at`),
  CONSTRAINT `fk_trading_fills_order` FOREIGN KEY (`trading_order_id`) REFERENCES `trading_orders` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_account_snapshots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `snapshot_key` char(64) NOT NULL,
  `snapshot_version` varchar(128) NOT NULL,
  `environment` varchar(16) NOT NULL DEFAULT 'SIMULATION',
  `provider` varchar(32) NOT NULL DEFAULT 'EASTMONEY_GM',
  `account_id` varchar(128) NOT NULL,
  `account_name` varchar(128) NOT NULL DEFAULT '',
  `nav` decimal(24,6) NOT NULL,
  `balance` decimal(24,6) NOT NULL,
  `available_cash` decimal(24,6) NOT NULL,
  `frozen_cash` decimal(24,6) NOT NULL DEFAULT 0,
  `market_value` decimal(24,6) NOT NULL DEFAULT 0,
  `floating_pnl` decimal(24,6) NOT NULL DEFAULT 0,
  `cumulative_pnl` decimal(24,6) NOT NULL DEFAULT 0,
  `cumulative_commission` decimal(24,6) NOT NULL DEFAULT 0,
  `terminal_state` varchar(32) NOT NULL,
  `account_state` varchar(32) NOT NULL,
  `snapshot_at` timestamp(3) NOT NULL,
  `received_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `raw_payload_json` json NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_account_snapshots_key` (`snapshot_key`),
  KEY `idx_trading_account_snapshots_account` (`account_id`,`snapshot_at`),
  KEY `idx_trading_account_snapshots_version` (`snapshot_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_position_snapshots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_snapshot_id` bigint NOT NULL,
  `account_id` varchar(128) NOT NULL,
  `symbol` varchar(32) NOT NULL,
  `eastmoney_symbol` varchar(32) NOT NULL,
  `position_side` varchar(16) NOT NULL DEFAULT 'LONG',
  `volume` bigint NOT NULL,
  `available_volume` bigint NOT NULL,
  `today_volume` bigint NOT NULL DEFAULT 0,
  `vwap` decimal(20,6) NOT NULL DEFAULT 0,
  `last_price` decimal(20,6) NOT NULL DEFAULT 0,
  `market_value` decimal(24,6) NOT NULL DEFAULT 0,
  `floating_pnl` decimal(24,6) NOT NULL DEFAULT 0,
  `raw_payload_json` json NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_position_snapshot` (`account_snapshot_id`,`eastmoney_symbol`,`position_side`),
  KEY `idx_trading_position_snapshots_account` (`account_id`,`eastmoney_symbol`),
  CONSTRAINT `fk_trading_position_snapshots_account` FOREIGN KEY (`account_snapshot_id`) REFERENCES `trading_account_snapshots` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_reconciliation_runs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_key` char(64) NOT NULL,
  `run_type` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'QUEUED',
  `account_id` varchar(128) NOT NULL,
  `bridge_cursor` varchar(255) NOT NULL DEFAULT '',
  `snapshot_version` varchar(128) NOT NULL DEFAULT '',
  `order_count` int NOT NULL DEFAULT 0,
  `fill_count` int NOT NULL DEFAULT 0,
  `position_count` int NOT NULL DEFAULT 0,
  `repaired_event_count` int NOT NULL DEFAULT 0,
  `repaired_fill_count` int NOT NULL DEFAULT 0,
  `diff_count` int NOT NULL DEFAULT 0,
  `request_json` json NOT NULL,
  `summary_json` json NOT NULL,
  `started_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `finished_at` timestamp(3) NULL DEFAULT NULL,
  `error_code` varchar(64) NOT NULL DEFAULT '',
  `error_message` text NOT NULL,
  `config_version` bigint NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_reconciliation_runs_key` (`run_key`),
  KEY `idx_trading_reconciliation_runs_status` (`status`,`started_at`),
  KEY `idx_trading_reconciliation_runs_account` (`account_id`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `trading_reconciliation_diffs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reconciliation_run_id` bigint NOT NULL,
  `diff_type` varchar(32) NOT NULL,
  `severity` varchar(16) NOT NULL,
  `entity_type` varchar(32) NOT NULL,
  `entity_key` varchar(255) NOT NULL,
  `field_name` varchar(128) NOT NULL DEFAULT '',
  `local_value_json` json NOT NULL,
  `provider_value_json` json NOT NULL,
  `resolution` varchar(32) NOT NULL DEFAULT 'OPEN',
  `resolution_message` text NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `resolved_at` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_trading_reconciliation_diffs_run` (`reconciliation_run_id`,`severity`),
  KEY `idx_trading_reconciliation_diffs_entity` (`entity_type`,`entity_key`),
  KEY `idx_trading_reconciliation_diffs_open` (`resolution`,`created_at`),
  CONSTRAINT `fk_trading_reconciliation_diffs_run` FOREIGN KEY (`reconciliation_run_id`) REFERENCES `trading_reconciliation_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Persistent application-level kill switch. Nacos remains the global switch,
-- and the Windows Bridge persists its own local switch independently.
CREATE TABLE IF NOT EXISTS `trading_runtime_controls` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `control_key` varchar(64) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `reason` text NOT NULL,
  `changed_by` varchar(128) NOT NULL,
  `config_version` bigint NOT NULL,
  `changed_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trading_runtime_controls_key` (`control_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `trading_runtime_controls`
  (`control_key`,`enabled`,`reason`,`changed_by`,`config_version`)
VALUES
  ('KILL_SWITCH',1,'initial deployment: fail closed','migration',0)
ON DUPLICATE KEY UPDATE `control_key`=VALUES(`control_key`);

CREATE TABLE IF NOT EXISTS `sector_trade_proxy_mappings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sector_symbol` varchar(32) NOT NULL,
  `sector_name` varchar(128) NOT NULL DEFAULT '',
  `proxy_security_master_id` bigint NOT NULL,
  `proxy_symbol` varchar(32) NOT NULL,
  `proxy_market` varchar(16) NOT NULL,
  `mapping_version` varchar(64) NOT NULL,
  `effective_from` date NOT NULL,
  `effective_to` date NULL DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 0,
  `reason` text NOT NULL,
  `created_by` varchar(128) NOT NULL,
  `approved_by` varchar(128) NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sector_trade_proxy_mapping` (`sector_symbol`,`proxy_security_master_id`,`effective_from`),
  KEY `idx_sector_trade_proxy_active` (`sector_symbol`,`enabled`,`effective_from`,`effective_to`),
  CONSTRAINT `fk_sector_trade_proxy_security` FOREIGN KEY (`proxy_security_master_id`) REFERENCES `security_master` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
