// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameBlogger = "bloggers"

// Blogger mapped from table <bloggers>
type Blogger struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;type:varchar(128);not null;index:idx_bloggers_name,priority:1" json:"name"`
	NormalizedName string    `gorm:"column:normalized_name;type:varchar(128);not null;uniqueIndex:uk_bloggers_normalized_institution,priority:1" json:"normalized_name"`
	Institution    string    `gorm:"column:institution;type:varchar(128);not null;uniqueIndex:uk_bloggers_normalized_institution,priority:2" json:"institution"`
	SourceType     string    `gorm:"column:source_type;type:varchar(32);not null;default:DOCUMENT" json:"source_type"`
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Blogger's table name
func (*Blogger) TableName() string {
	return TableNameBlogger
}
