// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import "time"

const TableNameConfigSnapshot = "config_snapshots"

type ConfigSnapshot struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConfigVersion int64     `gorm:"column:config_version;not null" json:"config_version"`
	Source        string    `gorm:"column:source;not null;type:varchar(128)" json:"source"`
	Sha256        string    `gorm:"column:sha256;not null;type:varchar(128)" json:"sha256"`
	RawJson       []byte    `gorm:"column:raw_json;not null;type:json" json:"raw_json"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

func (*ConfigSnapshot) TableName() string {
	return TableNameConfigSnapshot
}
