// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameConfigSnapshot = "config_snapshots"

// ConfigSnapshot mapped from table <config_snapshots>
type ConfigSnapshot struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ConfigVersion int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	Source        string    `gorm:"column:source;type:varchar(128);not null" json:"source"`
	Sha256        string    `gorm:"column:sha256;type:varchar(128);not null" json:"sha256"`
	RawJSON       []byte    `gorm:"column:raw_json;type:json;not null" json:"raw_json"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ConfigSnapshot's table name
func (*ConfigSnapshot) TableName() string {
	return TableNameConfigSnapshot
}
