// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import "time"

const TableNameDocument = "documents"

type Document struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Author        string    `gorm:"column:author;not null;type:varchar(128);default:''" json:"author"`
	Institution   string    `gorm:"column:institution;not null;type:varchar(128);default:''" json:"institution"`
	Title         string    `gorm:"column:title;not null;type:varchar(255);default:''" json:"title"`
	FileName      string    `gorm:"column:file_name;not null;type:varchar(255)" json:"file_name"`
	Sha256        string    `gorm:"column:sha256;not null;uniqueIndex:uk_documents_sha256;type:varchar(128)" json:"sha256"`
	PdfOcrEnabled bool      `gorm:"column:pdf_ocr_enabled;not null;default:0" json:"pdf_ocr_enabled"`
	Status        string    `gorm:"column:status;not null;index:idx_documents_status;type:varchar(64)" json:"status"`
	ConfigVersion int64     `gorm:"column:config_version;not null" json:"config_version"`
	RawContent    []byte    `gorm:"column:raw_content;not null;type:longblob" json:"raw_content"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;index:idx_documents_created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (*Document) TableName() string {
	return TableNameDocument
}
