// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameDocument = "documents"

// Document mapped from table <documents>
type Document struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Author        string    `gorm:"column:author;type:varchar(128);not null" json:"author"`
	Institution   string    `gorm:"column:institution;type:varchar(128);not null" json:"institution"`
	Title         string    `gorm:"column:title;type:varchar(255);not null" json:"title"`
	FileName      string    `gorm:"column:file_name;type:varchar(255);not null" json:"file_name"`
	Sha256        string    `gorm:"column:sha256;type:varchar(128);not null;uniqueIndex:uk_documents_sha256,priority:1" json:"sha256"`
	PdfOcrEnabled bool      `gorm:"column:pdf_ocr_enabled;type:tinyint(1);not null" json:"pdf_ocr_enabled"`
	Status        string    `gorm:"column:status;type:varchar(64);not null;index:idx_documents_status,priority:1" json:"status"`
	ConfigVersion int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	RawContent    []byte    `gorm:"column:raw_content;type:longblob;not null" json:"raw_content"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_documents_created_at,priority:1;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Document's table name
func (*Document) TableName() string {
	return TableNameDocument
}
