// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameExternalDocumentIngestion = "external_document_ingestions"

// ExternalDocumentIngestion mapped from table <external_document_ingestions>
type ExternalDocumentIngestion struct {
	ID               int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SourceType       int32      `gorm:"column:source_type;type:smallint unsigned;not null;uniqueIndex:uk_external_ingestion_source_version,priority:1" json:"source_type"`
	SourcePath       string     `gorm:"column:source_path;type:varchar(1024);not null" json:"source_path"`
	SourcePathHash   string     `gorm:"column:source_path_hash;type:char(64);not null;uniqueIndex:uk_external_ingestion_source_version,priority:2" json:"source_path_hash"`
	SourceVersion    string     `gorm:"column:source_version;type:varchar(191);not null;uniqueIndex:uk_external_ingestion_source_version,priority:3" json:"source_version"`
	FileName         string     `gorm:"column:file_name;type:varchar(512);not null" json:"file_name"`
	ArticleDate      time.Time  `gorm:"column:article_date;type:date;not null;index:idx_external_ingestion_article_date,priority:1" json:"article_date"`
	RemoteSize       int64      `gorm:"column:remote_size;type:bigint;not null" json:"remote_size"`
	RemoteModifiedAt *time.Time `gorm:"column:remote_modified_at;type:timestamp(3)" json:"remote_modified_at"`
	ContentSHA256    string     `gorm:"column:content_sha256;type:char(64);not null" json:"content_sha256"`
	DocumentID       *int64     `gorm:"column:document_id;type:bigint;index:idx_external_ingestion_document,priority:1" json:"document_id"`
	Status           int32      `gorm:"column:status;type:tinyint unsigned;not null;index:idx_external_ingestion_status_updated,priority:1" json:"status"`
	AttemptCount     int32      `gorm:"column:attempt_count;type:int unsigned;not null" json:"attempt_count"`
	LastError        string     `gorm:"column:last_error;type:text;not null" json:"last_error"`
	DiscoveredAt     time.Time  `gorm:"column:discovered_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"discovered_at"`
	DownloadedAt     *time.Time `gorm:"column:downloaded_at;type:timestamp(3)" json:"downloaded_at"`
	AnalyzedAt       *time.Time `gorm:"column:analyzed_at;type:timestamp(3)" json:"analyzed_at"`
	ConfigVersion    int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt        time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time  `gorm:"column:updated_at;type:timestamp;not null;index:idx_external_ingestion_status_updated,priority:2;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ExternalDocumentIngestion's table name
func (*ExternalDocumentIngestion) TableName() string {
	return TableNameExternalDocumentIngestion
}
