// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameInstrumentResolutionRun = "instrument_resolution_runs"

// InstrumentResolutionRun mapped from table <instrument_resolution_runs>
type InstrumentResolutionRun struct {
	ID                      int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	DocumentID              int64      `gorm:"column:document_id;type:bigint;not null;index:idx_resolution_runs_document,priority:1" json:"document_id"`
	ParseRunID              *int64     `gorm:"column:parse_run_id;type:bigint;index:idx_resolution_runs_parse_run,priority:1" json:"parse_run_id"`
	ConfigVersion           int64      `gorm:"column:config_version;type:bigint;not null;index:idx_resolution_runs_config_version,priority:1" json:"config_version"`
	AgentMode               string     `gorm:"column:agent_mode;type:varchar(32);not null;index:idx_resolution_runs_mode_status,priority:1" json:"agent_mode"`
	Route                   string     `gorm:"column:route;type:varchar(32);not null" json:"route"`
	Status                  string     `gorm:"column:status;type:varchar(32);not null;index:idx_resolution_runs_mode_status,priority:2;index:idx_resolution_runs_status,priority:1" json:"status"`
	SchemaVersion           string     `gorm:"column:schema_version;type:varchar(64);not null" json:"schema_version"`
	AgentVersion            string     `gorm:"column:agent_version;type:varchar(64);not null" json:"agent_version"`
	SkillName               string     `gorm:"column:skill_name;type:varchar(128);not null" json:"skill_name"`
	SkillVersion            string     `gorm:"column:skill_version;type:varchar(64);not null" json:"skill_version"`
	SkillHash               string     `gorm:"column:skill_hash;type:varchar(128);not null;index:idx_resolution_runs_skill_hash,priority:1" json:"skill_hash"`
	FallbackUsed            bool       `gorm:"column:fallback_used;type:tinyint(1);not null" json:"fallback_used"`
	RawTargetCount          int32      `gorm:"column:raw_target_count;type:int;not null" json:"raw_target_count"`
	CandidatePlanInputCount int32      `gorm:"column:candidate_plan_input_count;type:int;not null" json:"candidate_plan_input_count"`
	CandidatePlanCount      int32      `gorm:"column:candidate_plan_count;type:int;not null" json:"candidate_plan_count"`
	UntrackableCount        int32      `gorm:"column:untrackable_count;type:int;not null" json:"untrackable_count"`
	ToolCallCount           int32      `gorm:"column:tool_call_count;type:int;not null" json:"tool_call_count"`
	ErrorCode               string     `gorm:"column:error_code;type:varchar(64);not null" json:"error_code"`
	ErrorMessage            string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	StartedAt               time.Time  `gorm:"column:started_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"started_at"`
	FinishedAt              *time.Time `gorm:"column:finished_at;type:timestamp(3)" json:"finished_at"`
	DurationMs              int32      `gorm:"column:duration_ms;type:int;not null" json:"duration_ms"`
	TargetsJSON             []byte     `gorm:"column:targets_json;type:json;not null" json:"targets_json"`
	ToolTracesJSON          []byte     `gorm:"column:tool_traces_json;type:json;not null" json:"tool_traces_json"`
	ShadowCompareJSON       []byte     `gorm:"column:shadow_compare_json;type:json;not null" json:"shadow_compare_json"`
	RawMetadataJSON         []byte     `gorm:"column:raw_metadata_json;type:json;not null" json:"raw_metadata_json"`
	CreatedAt               time.Time  `gorm:"column:created_at;type:timestamp;not null;index:idx_resolution_runs_document,priority:2;index:idx_resolution_runs_mode_status,priority:3;index:idx_resolution_runs_status,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt               time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName InstrumentResolutionRun's table name
func (*InstrumentResolutionRun) TableName() string {
	return TableNameInstrumentResolutionRun
}
