// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameMarketDataSyncRun = "market_data_sync_runs"

// MarketDataSyncRun mapped from table <market_data_sync_runs>
type MarketDataSyncRun struct {
	ID                int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SyncType          string     `gorm:"column:sync_type;type:varchar(64);not null;index:idx_market_sync_runs_claim,priority:1;index:idx_market_sync_runs_type_date,priority:1" json:"sync_type"`
	Provider          string     `gorm:"column:provider;type:varchar(32);not null;default:TUSHARE" json:"provider"`
	TradeDate         time.Time  `gorm:"column:trade_date;type:date;index:idx_market_sync_runs_type_date,priority:2" json:"trade_date"`
	Status            string     `gorm:"column:status;type:varchar(32);not null;index:idx_market_sync_runs_claim,priority:2;index:idx_market_sync_runs_status,priority:1" json:"status"`
	ExpectedCount     int32      `gorm:"column:expected_count;type:int;not null" json:"expected_count"`
	FetchedCount      int32      `gorm:"column:fetched_count;type:int;not null" json:"fetched_count"`
	MatchedCount      int32      `gorm:"column:matched_count;type:int;not null" json:"matched_count"`
	UpsertedCount     int32      `gorm:"column:upserted_count;type:int;not null" json:"upserted_count"`
	MissingCount      int32      `gorm:"column:missing_count;type:int;not null" json:"missing_count"`
	FailedCount       int32      `gorm:"column:failed_count;type:int;not null" json:"failed_count"`
	TokenAlias        string     `gorm:"column:token_alias;type:varchar(64);not null" json:"token_alias"`
	RequestParamsJSON []byte     `gorm:"column:request_params_json;type:json;not null" json:"request_params_json"`
	ErrorCode         string     `gorm:"column:error_code;type:varchar(64);not null" json:"error_code"`
	ErrorMessage      string     `gorm:"column:error_message;type:text" json:"error_message"`
	QueuedAt          time.Time  `gorm:"column:queued_at;type:timestamp;not null;index:idx_market_sync_runs_claim,priority:3;default:CURRENT_TIMESTAMP" json:"queued_at"`
	StartedAt         *time.Time `gorm:"column:started_at;type:timestamp" json:"started_at"`
	FinishedAt        *time.Time `gorm:"column:finished_at;type:timestamp" json:"finished_at"`
	ClaimedBy         string     `gorm:"column:claimed_by;type:varchar(128);not null" json:"claimed_by"`
	ClaimedAt         *time.Time `gorm:"column:claimed_at;type:timestamp" json:"claimed_at"`
	ConfigVersion     int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt         time.Time  `gorm:"column:created_at;type:timestamp;not null;index:idx_market_sync_runs_status,priority:2;index:idx_market_sync_runs_type_date,priority:3;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MarketDataSyncRun's table name
func (*MarketDataSyncRun) TableName() string {
	return TableNameMarketDataSyncRun
}
