// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameMarketDataSyncMissingItem = "market_data_sync_missing_items"

// MarketDataSyncMissingItem mapped from table <market_data_sync_missing_items>
type MarketDataSyncMissingItem struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SyncRunID        int64     `gorm:"column:sync_run_id;type:bigint;not null;uniqueIndex:uk_market_sync_missing_run_ts_date,priority:1" json:"sync_run_id"`
	SecurityMasterID *int64    `gorm:"column:security_master_id;type:bigint;index:fk_market_missing_security_sector,priority:1" json:"security_master_id"`
	TSCode           string    `gorm:"column:ts_code;type:varchar(16);not null;uniqueIndex:uk_market_sync_missing_run_ts_date,priority:2;index:idx_market_sync_missing_ts_date,priority:1" json:"ts_code"`
	Symbol           string    `gorm:"column:symbol;type:varchar(16);not null" json:"symbol"`
	SecurityName     string    `gorm:"column:security_name;type:varchar(128);not null" json:"security_name"`
	TradeDate        time.Time `gorm:"column:trade_date;type:date;not null;uniqueIndex:uk_market_sync_missing_run_ts_date,priority:3;index:idx_market_sync_missing_ts_date,priority:2" json:"trade_date"`
	Reason           string    `gorm:"column:reason;type:varchar(64);not null" json:"reason"`
	Message          string    `gorm:"column:message;type:varchar(255);not null" json:"message"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName MarketDataSyncMissingItem's table name
func (*MarketDataSyncMissingItem) TableName() string {
	return TableNameMarketDataSyncMissingItem
}
