// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameParseRun = "parse_runs"

// ParseRun mapped from table <parse_runs>
type ParseRun struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	DocumentID      int64     `gorm:"column:document_id;type:bigint;not null;index:idx_parse_runs_document,priority:1" json:"document_id"`
	Status          string    `gorm:"column:status;type:varchar(64);not null" json:"status"`
	ParserName      string    `gorm:"column:parser_name;type:varchar(128);not null" json:"parser_name"`
	ParserVersion   string    `gorm:"column:parser_version;type:varchar(64);not null" json:"parser_version"`
	ErrorMessage    string    `gorm:"column:error_message;type:text;not null" json:"error_message"`
	CleanedText     string    `gorm:"column:cleaned_text;type:longtext;not null" json:"cleaned_text"`
	ChunksJSON      []byte    `gorm:"column:chunks_json;type:json;not null" json:"chunks_json"`
	RawMetadataJSON []byte    `gorm:"column:raw_metadata_json;type:json;not null" json:"raw_metadata_json"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_parse_runs_document,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ParseRun's table name
func (*ParseRun) TableName() string {
	return TableNameParseRun
}
