// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import "time"

const TableNameParseRun = "parse_runs"

type ParseRun struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DocumentID      int64     `gorm:"column:document_id;not null;index:idx_parse_runs_document,priority:1" json:"document_id"`
	Status          string    `gorm:"column:status;not null;type:varchar(64)" json:"status"`
	ParserName      string    `gorm:"column:parser_name;not null;type:varchar(128)" json:"parser_name"`
	ParserVersion   string    `gorm:"column:parser_version;not null;type:varchar(64)" json:"parser_version"`
	ErrorMessage    string    `gorm:"column:error_message;not null;type:text" json:"error_message"`
	CleanedText     string    `gorm:"column:cleaned_text;not null;type:longtext" json:"cleaned_text"`
	ChunksJson      []byte    `gorm:"column:chunks_json;not null;type:json" json:"chunks_json"`
	RawMetadataJson []byte    `gorm:"column:raw_metadata_json;not null;type:json" json:"raw_metadata_json"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;index:idx_parse_runs_document,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (*ParseRun) TableName() string {
	return TableNameParseRun
}
