// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameRecommendationEventWindowMetric = "recommendation_event_window_metrics"

// RecommendationEventWindowMetric mapped from table <recommendation_event_window_metrics>
type RecommendationEventWindowMetric struct {
	ID                      int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RecommendationEventID   int64      `gorm:"column:recommendation_event_id;type:bigint;not null;uniqueIndex:uk_rec_window_metric,priority:1" json:"recommendation_event_id"`
	BloggerID               int64      `gorm:"column:blogger_id;type:bigint;not null;index:idx_rec_window_metric_blogger,priority:1" json:"blogger_id"`
	SecurityMasterID        int64      `gorm:"column:security_master_id;type:bigint;not null;index:idx_rec_window_metric_security,priority:1" json:"security_master_id"`
	TSCode                  string     `gorm:"column:ts_code;type:varchar(16);not null" json:"ts_code"`
	Symbol                  string     `gorm:"column:symbol;type:varchar(32);not null;index:idx_rec_window_metric_symbol,priority:1" json:"symbol"`
	SecurityName            string     `gorm:"column:security_name;type:varchar(128);not null" json:"security_name"`
	AssetType               string     `gorm:"column:asset_type;type:varchar(32);not null" json:"asset_type"`
	Market                  string     `gorm:"column:market;type:varchar(32);not null" json:"market"`
	Industry                string     `gorm:"column:industry;type:varchar(128);not null" json:"industry"`
	Direction               string     `gorm:"column:direction;type:varchar(16);not null" json:"direction"`
	RecommendDate           time.Time  `gorm:"column:recommend_date;type:date;not null;index:idx_rec_window_metric_blogger,priority:4;index:idx_rec_window_metric_security,priority:3;index:idx_rec_window_metric_symbol,priority:3" json:"recommend_date"`
	WindowDays              int32      `gorm:"column:window_days;type:int;not null;uniqueIndex:uk_rec_window_metric,priority:2;index:idx_rec_window_metric_blogger,priority:2;index:idx_rec_window_metric_rank,priority:1;index:idx_rec_window_metric_security,priority:2;index:idx_rec_window_metric_symbol,priority:2" json:"window_days"`
	QuoteSource             string     `gorm:"column:quote_source;type:varchar(32);not null;uniqueIndex:uk_rec_window_metric,priority:3;default:TUSHARE" json:"quote_source"`
	Status                  string     `gorm:"column:status;type:varchar(32);not null;index:idx_rec_window_metric_blogger,priority:3;index:idx_rec_window_metric_rank,priority:2" json:"status"`
	ReasonCode              string     `gorm:"column:reason_code;type:varchar(64);not null" json:"reason_code"`
	ReasonMessage           string     `gorm:"column:reason_message;type:text;not null" json:"reason_message"`
	BaseDate                *time.Time `gorm:"column:base_date;type:date" json:"base_date"`
	BaseClosePrice          *float64   `gorm:"column:base_close_price;type:decimal(18,4)" json:"base_close_price"`
	EntryDate               *time.Time `gorm:"column:entry_date;type:date" json:"entry_date"`
	EntryPrice              *float64   `gorm:"column:entry_price;type:decimal(18,4)" json:"entry_price"`
	ExitDate                *time.Time `gorm:"column:exit_date;type:date" json:"exit_date"`
	ExitClosePrice          *float64   `gorm:"column:exit_close_price;type:decimal(18,4)" json:"exit_close_price"`
	ExpectedQuoteCount      int32      `gorm:"column:expected_quote_count;type:int;not null" json:"expected_quote_count"`
	ActualQuoteCount        int32      `gorm:"column:actual_quote_count;type:int;not null" json:"actual_quote_count"`
	MissingQuoteCount       int32      `gorm:"column:missing_quote_count;type:int;not null" json:"missing_quote_count"`
	RawReturnRatio          *float64   `gorm:"column:raw_return_ratio;type:decimal(18,8)" json:"raw_return_ratio"`
	DirectionReturnRatio    *float64   `gorm:"column:direction_return_ratio;type:decimal(18,8);index:idx_rec_window_metric_rank,priority:3" json:"direction_return_ratio"`
	MaxFavorableReturnRatio *float64   `gorm:"column:max_favorable_return_ratio;type:decimal(18,8)" json:"max_favorable_return_ratio"`
	MaxAdverseReturnRatio   *float64   `gorm:"column:max_adverse_return_ratio;type:decimal(18,8)" json:"max_adverse_return_ratio"`
	MaxDrawdownRatio        *float64   `gorm:"column:max_drawdown_ratio;type:decimal(18,8)" json:"max_drawdown_ratio"`
	WinFlag                 *bool      `gorm:"column:win_flag;type:tinyint(1)" json:"win_flag"`
	BestTradeDate           *time.Time `gorm:"column:best_trade_date;type:date" json:"best_trade_date"`
	WorstTradeDate          *time.Time `gorm:"column:worst_trade_date;type:date" json:"worst_trade_date"`
	EvaluationRunID         int64      `gorm:"column:evaluation_run_id;type:bigint;not null" json:"evaluation_run_id"`
	CalcVersion             string     `gorm:"column:calc_version;type:varchar(64);not null" json:"calc_version"`
	ConfigVersion           int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CalculatedAt            time.Time  `gorm:"column:calculated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"calculated_at"`
	CreatedAt               time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt               time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RecommendationEventWindowMetric's table name
func (*RecommendationEventWindowMetric) TableName() string {
	return TableNameRecommendationEventWindowMetric
}
