// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameRecommendationEvent = "recommendation_events"

// RecommendationEvent mapped from table <recommendation_events>
type RecommendationEvent struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BloggerID        int64     `gorm:"column:blogger_id;type:bigint;not null;index:idx_recommendation_events_blogger_date,priority:1" json:"blogger_id"`
	SourceDocumentID int64     `gorm:"column:source_document_id;type:bigint;not null;index:idx_recommendation_events_document,priority:1" json:"source_document_id"`
	PlanID           int64     `gorm:"column:plan_id;type:bigint;not null;index:idx_recommendation_events_plan,priority:1" json:"plan_id"`
	ParseRunID       int64     `gorm:"column:parse_run_id;type:bigint;not null;index:fk_recommendation_events_parse_run,priority:1" json:"parse_run_id"`
	Symbol           string    `gorm:"column:symbol;type:varchar(32);not null;index:idx_recommendation_events_symbol_date,priority:1" json:"symbol"`
	AssetType        string    `gorm:"column:asset_type;type:varchar(32);not null" json:"asset_type"`
	Market           string    `gorm:"column:market;type:varchar(32);not null" json:"market"`
	Direction        string    `gorm:"column:direction;type:varchar(16);not null" json:"direction"`
	RecommendDate    time.Time `gorm:"column:recommend_date;type:date;not null;index:idx_recommendation_events_blogger_date,priority:2;index:idx_recommendation_events_symbol_date,priority:2" json:"recommend_date"`
	ReferencePrice   float64   `gorm:"column:reference_price;type:double;not null" json:"reference_price"`
	Confidence       float64   `gorm:"column:confidence;type:double;not null" json:"confidence"`
	Status           string    `gorm:"column:status;type:varchar(64);not null" json:"status"`
	Thesis           string    `gorm:"column:thesis;type:text;not null" json:"thesis"`
	DedupeKey        string    `gorm:"column:dedupe_key;type:varchar(128);not null;uniqueIndex:uk_recommendation_events_dedupe_key,priority:1" json:"dedupe_key"`
	ConfigVersion    int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	RuleVersion      string    `gorm:"column:rule_version;type:varchar(64);not null" json:"rule_version"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_recommendation_events_document,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RecommendationEvent's table name
func (*RecommendationEvent) TableName() string {
	return TableNameRecommendationEvent
}
