// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameScheduledTaskRun = "scheduled_task_runs"

// ScheduledTaskRun mapped from table <scheduled_task_runs>
type ScheduledTaskRun struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TaskType      uint16     `gorm:"column:task_type;type:smallint unsigned;not null;uniqueIndex:uk_scheduled_task_runs_type_key,priority:1;index:idx_scheduled_task_runs_type_created,priority:1" json:"task_type"`
	TaskKey       string     `gorm:"column:task_key;type:varchar(128);not null;uniqueIndex:uk_scheduled_task_runs_type_key,priority:2" json:"task_key"`
	Status        string     `gorm:"column:status;type:varchar(32);not null;index:idx_scheduled_task_runs_claim,priority:1;default:QUEUED" json:"status"`
	ScheduledAt   time.Time  `gorm:"column:scheduled_at;type:timestamp(3);not null;index:idx_scheduled_task_runs_claim,priority:2" json:"scheduled_at"`
	InputJSON     []byte     `gorm:"column:input_json;type:json;not null" json:"input_json"`
	OutputJSON    []byte     `gorm:"column:output_json;type:json" json:"output_json"`
	ErrorMessage  string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	WorkerID      string     `gorm:"column:worker_id;type:varchar(128);not null" json:"worker_id"`
	AttemptCount  int32      `gorm:"column:attempt_count;type:int;not null" json:"attempt_count"`
	StartedAt     *time.Time `gorm:"column:started_at;type:timestamp(3)" json:"started_at"`
	FinishedAt    *time.Time `gorm:"column:finished_at;type:timestamp(3)" json:"finished_at"`
	ConfigVersion int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt     time.Time  `gorm:"column:created_at;type:timestamp;not null;index:idx_scheduled_task_runs_type_created,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ScheduledTaskRun's table name
func (*ScheduledTaskRun) TableName() string {
	return TableNameScheduledTaskRun
}
