// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSectorTradeProxyMapping = "sector_trade_proxy_mappings"

// SectorTradeProxyMapping mapped from table <sector_trade_proxy_mappings>
type SectorTradeProxyMapping struct {
	ID                    int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SectorSymbol          string     `gorm:"column:sector_symbol;type:varchar(32);not null;uniqueIndex:uk_sector_trade_proxy_mapping,priority:1;index:idx_sector_trade_proxy_active,priority:1" json:"sector_symbol"`
	SectorName            string     `gorm:"column:sector_name;type:varchar(128);not null" json:"sector_name"`
	ProxySecurityMasterID int64      `gorm:"column:proxy_security_master_id;type:bigint;not null;uniqueIndex:uk_sector_trade_proxy_mapping,priority:2;index:fk_sector_trade_proxy_security,priority:1" json:"proxy_security_master_id"`
	ProxySymbol           string     `gorm:"column:proxy_symbol;type:varchar(32);not null" json:"proxy_symbol"`
	ProxyMarket           string     `gorm:"column:proxy_market;type:varchar(16);not null" json:"proxy_market"`
	MappingVersion        string     `gorm:"column:mapping_version;type:varchar(64);not null" json:"mapping_version"`
	EffectiveFrom         time.Time  `gorm:"column:effective_from;type:date;not null;uniqueIndex:uk_sector_trade_proxy_mapping,priority:3;index:idx_sector_trade_proxy_active,priority:3" json:"effective_from"`
	EffectiveTo           *time.Time `gorm:"column:effective_to;type:date;index:idx_sector_trade_proxy_active,priority:4" json:"effective_to"`
	Enabled               bool       `gorm:"column:enabled;type:tinyint(1);not null;index:idx_sector_trade_proxy_active,priority:2" json:"enabled"`
	Reason                string     `gorm:"column:reason;type:text;not null" json:"reason"`
	CreatedBy             string     `gorm:"column:created_by;type:varchar(128);not null" json:"created_by"`
	ApprovedBy            string     `gorm:"column:approved_by;type:varchar(128);not null" json:"approved_by"`
	CreatedAt             time.Time  `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt             time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName SectorTradeProxyMapping's table name
func (*SectorTradeProxyMapping) TableName() string {
	return TableNameSectorTradeProxyMapping
}
