// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSecurityMaster = "security_master"

// SecurityMaster mapped from table <security_master>
type SecurityMaster struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TSCode     string     `gorm:"column:ts_code;type:varchar(16);not null;uniqueIndex:uk_security_master_ts_code,priority:1" json:"ts_code"`
	Symbol     string     `gorm:"column:symbol;type:varchar(16);not null;index:idx_security_master_market_symbol,priority:2;index:idx_security_master_symbol,priority:1" json:"symbol"`
	Name       string     `gorm:"column:name;type:varchar(128);not null;index:idx_security_master_name,priority:1" json:"name"`
	FullName   string     `gorm:"column:full_name;type:varchar(255);not null" json:"full_name"`
	Exchange   string     `gorm:"column:exchange;type:varchar(16);not null" json:"exchange"`
	Market     string     `gorm:"column:market;type:varchar(16);not null;index:idx_security_master_market_symbol,priority:1" json:"market"`
	AssetType  string     `gorm:"column:asset_type;type:varchar(32);not null;index:idx_security_master_asset_status,priority:1" json:"asset_type"`
	ListStatus string     `gorm:"column:list_status;type:varchar(8);not null;index:idx_security_master_asset_status,priority:2;default:L" json:"list_status"`
	ListDate   *time.Time `gorm:"column:list_date;type:date" json:"list_date"`
	DelistDate *time.Time `gorm:"column:delist_date;type:date" json:"delist_date"`
	Industry   string     `gorm:"column:industry;type:varchar(128);not null" json:"industry"`
	SectorType string     `gorm:"column:sector_type;type:varchar(32);not null" json:"sector_type"`
	IsActive   bool       `gorm:"column:is_active;type:tinyint(1);not null;index:idx_security_master_asset_status,priority:3;default:1" json:"is_active"`
	Source     string     `gorm:"column:source;type:varchar(32);not null;default:MANUAL" json:"source"`
	RawJSON    []byte     `gorm:"column:raw_json;type:json;not null" json:"raw_json"`
	CreatedAt  time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SecurityMaster's table name
func (*SecurityMaster) TableName() string {
	return TableNameSecurityMaster
}
