// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSecurityAlias = "security_aliases"

// SecurityAlias mapped from table <security_aliases>
type SecurityAlias struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SecurityMasterID int64     `gorm:"column:security_master_id;type:bigint;not null;uniqueIndex:uk_security_aliases_alias_master_type,priority:2;index:idx_security_aliases_master,priority:1" json:"security_master_id"`
	AliasName        string    `gorm:"column:alias;type:varchar(128);not null" json:"alias"`
	NormalizedAlias  string    `gorm:"column:normalized_alias;type:varchar(128);not null;uniqueIndex:uk_security_aliases_alias_master_type,priority:1;index:idx_security_aliases_normalized_active,priority:1" json:"normalized_alias"`
	AliasType        string    `gorm:"column:alias_type;type:varchar(32);not null;uniqueIndex:uk_security_aliases_alias_master_type,priority:3;default:MANUAL" json:"alias_type"`
	Source           string    `gorm:"column:source;type:varchar(32);not null;default:MANUAL" json:"source"`
	Confidence       float64   `gorm:"column:confidence;type:double;not null;default:1" json:"confidence"`
	IsActive         bool      `gorm:"column:is_active;type:tinyint(1);not null;index:idx_security_aliases_normalized_active,priority:2;default:1" json:"is_active"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SecurityAlias's table name
func (*SecurityAlias) TableName() string {
	return TableNameSecurityAlias
}
