// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameStockDailyQuote = "stock_daily_quotes"

// StockDailyQuote mapped from table <stock_daily_quotes>
type StockDailyQuote struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SecurityMasterID int64     `gorm:"column:security_master_id;type:bigint;not null;index:idx_stock_daily_quotes_security_date,priority:1" json:"security_master_id"`
	TSCode           string    `gorm:"column:ts_code;type:varchar(16);not null;uniqueIndex:uk_stock_daily_quotes_ts_date_source,priority:1" json:"ts_code"`
	Symbol           string    `gorm:"column:symbol;type:varchar(16);not null;index:idx_stock_daily_quotes_symbol_date,priority:1" json:"symbol"`
	SecurityName     string    `gorm:"column:security_name;type:varchar(128);not null" json:"security_name"`
	Exchange         string    `gorm:"column:exchange;type:varchar(16);not null" json:"exchange"`
	Market           string    `gorm:"column:market;type:varchar(16);not null;index:idx_stock_daily_quotes_market_date,priority:1" json:"market"`
	AssetType        string    `gorm:"column:asset_type;type:varchar(32);not null;default:STOCK" json:"asset_type"`
	Industry         string    `gorm:"column:industry;type:varchar(128);not null;index:idx_stock_daily_quotes_industry_date,priority:1" json:"industry"`
	SectorType       string    `gorm:"column:sector_type;type:varchar(32);not null" json:"sector_type"`
	ListStatus       string    `gorm:"column:list_status;type:varchar(8);not null;default:L" json:"list_status"`
	TradeDate        time.Time `gorm:"column:trade_date;type:date;not null;uniqueIndex:uk_stock_daily_quotes_ts_date_source,priority:2;index:idx_stock_daily_quotes_industry_date,priority:2;index:idx_stock_daily_quotes_market_date,priority:2;index:idx_stock_daily_quotes_pct_chg,priority:1;index:idx_stock_daily_quotes_security_date,priority:2;index:idx_stock_daily_quotes_symbol_date,priority:2;index:idx_stock_daily_quotes_trade_date,priority:1" json:"trade_date"`
	OpenPrice        float64   `gorm:"column:open_price;type:decimal(18,4)" json:"open_price"`
	HighPrice        float64   `gorm:"column:high_price;type:decimal(18,4)" json:"high_price"`
	LowPrice         float64   `gorm:"column:low_price;type:decimal(18,4)" json:"low_price"`
	ClosePrice       float64   `gorm:"column:close_price;type:decimal(18,4)" json:"close_price"`
	PreClosePrice    float64   `gorm:"column:pre_close_price;type:decimal(18,4)" json:"pre_close_price"`
	ChangeAmount     float64   `gorm:"column:change_amount;type:decimal(18,4)" json:"change_amount"`
	PctChg           float64   `gorm:"column:pct_chg;type:decimal(18,6);index:idx_stock_daily_quotes_pct_chg,priority:2" json:"pct_chg"`
	Volume           float64   `gorm:"column:volume;type:decimal(24,4)" json:"volume"`
	Amount           float64   `gorm:"column:amount;type:decimal(24,4)" json:"amount"`
	Source           string    `gorm:"column:source;type:varchar(32);not null;uniqueIndex:uk_stock_daily_quotes_ts_date_source,priority:3;default:TUSHARE" json:"source"`
	TushareContent   []byte    `gorm:"column:tushare_content;type:json;not null" json:"tushare_content"`
	ConfigVersion    int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StockDailyQuote's table name
func (*StockDailyQuote) TableName() string {
	return TableNameStockDailyQuote
}
