// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingAccountSnapshot = "trading_account_snapshots"

// TradingAccountSnapshot mapped from table <trading_account_snapshots>
type TradingAccountSnapshot struct {
	ID                   int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SnapshotKey          string    `gorm:"column:snapshot_key;type:char(64);not null;uniqueIndex:uk_trading_account_snapshots_key,priority:1" json:"snapshot_key"`
	SnapshotVersion      string    `gorm:"column:snapshot_version;type:varchar(128);not null;index:idx_trading_account_snapshots_version,priority:1" json:"snapshot_version"`
	Environment          string    `gorm:"column:environment;type:varchar(16);not null;default:SIMULATION" json:"environment"`
	Provider             string    `gorm:"column:provider;type:varchar(32);not null;default:EASTMONEY_GM" json:"provider"`
	AccountID            string    `gorm:"column:account_id;type:varchar(128);not null;index:idx_trading_account_snapshots_account,priority:1" json:"account_id"`
	AccountName          string    `gorm:"column:account_name;type:varchar(128);not null" json:"account_name"`
	Nav                  string    `gorm:"column:nav;type:decimal(24,6);not null" json:"nav"`
	Balance              string    `gorm:"column:balance;type:decimal(24,6);not null" json:"balance"`
	AvailableCash        string    `gorm:"column:available_cash;type:decimal(24,6);not null" json:"available_cash"`
	FrozenCash           string    `gorm:"column:frozen_cash;type:decimal(24,6);not null;default:0.000000" json:"frozen_cash"`
	MarketValue          string    `gorm:"column:market_value;type:decimal(24,6);not null;default:0.000000" json:"market_value"`
	FloatingPnl          string    `gorm:"column:floating_pnl;type:decimal(24,6);not null;default:0.000000" json:"floating_pnl"`
	CumulativeInout      string    `gorm:"column:cumulative_inout;type:decimal(24,6);not null;default:0.000000" json:"cumulative_inout"`
	CumulativeTrade      string    `gorm:"column:cumulative_trade;type:decimal(24,6);not null;default:0.000000" json:"cumulative_trade"`
	CumulativePnl        string    `gorm:"column:cumulative_pnl;type:decimal(24,6);not null;default:0.000000" json:"cumulative_pnl"`
	CumulativeCommission string    `gorm:"column:cumulative_commission;type:decimal(24,6);not null;default:0.000000" json:"cumulative_commission"`
	LastTrade            string    `gorm:"column:last_trade;type:decimal(24,6);not null;default:0.000000" json:"last_trade"`
	LastPnl              string    `gorm:"column:last_pnl;type:decimal(24,6);not null;default:0.000000" json:"last_pnl"`
	LastCommission       string    `gorm:"column:last_commission;type:decimal(24,6);not null;default:0.000000" json:"last_commission"`
	CommissionDataStatus string    `gorm:"column:commission_data_status;type:varchar(32);not null;default:UNAVAILABLE" json:"commission_data_status"`
	TerminalState        string    `gorm:"column:terminal_state;type:varchar(32);not null" json:"terminal_state"`
	AccountState         string    `gorm:"column:account_state;type:varchar(32);not null" json:"account_state"`
	SnapshotAt           time.Time `gorm:"column:snapshot_at;type:timestamp(3);not null;index:idx_trading_account_snapshots_account,priority:2" json:"snapshot_at"`
	ReceivedAt           time.Time `gorm:"column:received_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"received_at"`
	RawPayloadJSON       []byte    `gorm:"column:raw_payload_json;type:json;not null" json:"raw_payload_json"`
	CreatedAt            time.Time `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TradingAccountSnapshot's table name
func (*TradingAccountSnapshot) TableName() string {
	return TableNameTradingAccountSnapshot
}
