// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingFill = "trading_fills"

// TradingFill mapped from table <trading_fills>
type TradingFill struct {
	ID                     int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TradingOrderID         int64      `gorm:"column:trading_order_id;type:bigint;not null;index:idx_trading_fills_order,priority:1" json:"trading_order_id"`
	AccountID              string     `gorm:"column:account_id;type:varchar(128);not null;uniqueIndex:uk_trading_fills_exec,priority:1" json:"account_id"`
	ExecID                 string     `gorm:"column:exec_id;type:varchar(128);not null;uniqueIndex:uk_trading_fills_exec,priority:2" json:"exec_id"`
	ClOrdID                string     `gorm:"column:cl_ord_id;type:varchar(128);not null" json:"cl_ord_id"`
	Symbol                 string     `gorm:"column:symbol;type:varchar(32);not null;index:idx_trading_fills_symbol,priority:1" json:"symbol"`
	EastmoneySymbol        string     `gorm:"column:eastmoney_symbol;type:varchar(32);not null" json:"eastmoney_symbol"`
	Side                   string     `gorm:"column:side;type:varchar(16);not null" json:"side"`
	Price                  string     `gorm:"column:price;type:decimal(20,6);not null" json:"price"`
	Volume                 int64      `gorm:"column:volume;type:bigint;not null" json:"volume"`
	Amount                 string     `gorm:"column:amount;type:decimal(24,6);not null" json:"amount"`
	Commission             string     `gorm:"column:commission;type:decimal(20,6);not null;default:0.000000" json:"commission"`
	CommissionStatus       string     `gorm:"column:commission_status;type:varchar(32);not null;index:idx_trading_fills_commission_status,priority:1;default:PENDING" json:"commission_status"`
	CommissionSource       string     `gorm:"column:commission_source;type:varchar(64);not null" json:"commission_source"`
	CommissionEvidenceJSON []byte     `gorm:"column:commission_evidence_json;type:json" json:"commission_evidence_json"`
	CommissionReconciledAt *time.Time `gorm:"column:commission_reconciled_at;type:timestamp(3)" json:"commission_reconciled_at"`
	ExecType               string     `gorm:"column:exec_type;type:varchar(32);not null" json:"exec_type"`
	TradedAt               time.Time  `gorm:"column:traded_at;type:timestamp(3);not null;index:idx_trading_fills_commission_status,priority:2;index:idx_trading_fills_order,priority:2;index:idx_trading_fills_symbol,priority:2" json:"traded_at"`
	RawPayloadJSON         []byte     `gorm:"column:raw_payload_json;type:json;not null" json:"raw_payload_json"`
	CreatedAt              time.Time  `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TradingFill's table name
func (*TradingFill) TableName() string {
	return TableNameTradingFill
}
