// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingOrderEvent = "trading_order_events"

// TradingOrderEvent mapped from table <trading_order_events>
type TradingOrderEvent struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TradingOrderID   int64     `gorm:"column:trading_order_id;type:bigint;not null;index:idx_trading_order_events_order,priority:1" json:"trading_order_id"`
	EventHash        string    `gorm:"column:event_hash;type:char(64);not null;uniqueIndex:uk_trading_order_events_hash,priority:1" json:"event_hash"`
	EventType        string    `gorm:"column:event_type;type:varchar(32);not null" json:"event_type"`
	Source           string    `gorm:"column:source;type:varchar(32);not null;default:BRIDGE_CALLBACK" json:"source"`
	AccountID        string    `gorm:"column:account_id;type:varchar(128);not null;index:idx_trading_order_events_cl_ord,priority:1" json:"account_id"`
	ClOrdID          string    `gorm:"column:cl_ord_id;type:varchar(128);not null;index:idx_trading_order_events_cl_ord,priority:2" json:"cl_ord_id"`
	ProviderStatus   string    `gorm:"column:provider_status;type:varchar(32);not null" json:"provider_status"`
	NormalizedStatus string    `gorm:"column:normalized_status;type:varchar(32);not null" json:"normalized_status"`
	FilledVolume     int64     `gorm:"column:filled_volume;type:bigint;not null" json:"filled_volume"`
	FilledVwap       *string   `gorm:"column:filled_vwap;type:decimal(20,6)" json:"filled_vwap"`
	EventAt          time.Time `gorm:"column:event_at;type:timestamp(3);not null;index:idx_trading_order_events_cl_ord,priority:3;index:idx_trading_order_events_order,priority:2" json:"event_at"`
	ReceivedAt       time.Time `gorm:"column:received_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"received_at"`
	RawPayloadJSON   []byte    `gorm:"column:raw_payload_json;type:json;not null" json:"raw_payload_json"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TradingOrderEvent's table name
func (*TradingOrderEvent) TableName() string {
	return TableNameTradingOrderEvent
}
