// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import "time"

const TableNameTradeCandidatePlan = "trade_candidate_plans"

type TradeCandidatePlan struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DocumentID     int64     `gorm:"column:document_id;not null;index:idx_trade_candidate_plans_document,priority:1" json:"document_id"`
	ParseRunID     int64     `gorm:"column:parse_run_id;not null;index:fk_trade_candidate_plans_parse_run" json:"parse_run_id"`
	Analyst        string    `gorm:"column:analyst;not null;type:varchar(128)" json:"analyst"`
	Institution    string    `gorm:"column:institution;not null;type:varchar(128);default:''" json:"institution"`
	Symbol         string    `gorm:"column:symbol;not null;index:idx_trade_candidate_plans_symbol_trade_date,priority:1;type:varchar(32)" json:"symbol"`
	AssetType      string    `gorm:"column:asset_type;not null;type:varchar(32)" json:"asset_type"`
	Market         string    `gorm:"column:market;not null;type:varchar(32)" json:"market"`
	Strategy       string    `gorm:"column:strategy;not null;type:varchar(64)" json:"strategy"`
	Direction      string    `gorm:"column:direction;not null;type:varchar(16)" json:"direction"`
	TradeDate      time.Time `gorm:"column:trade_date;not null;index:idx_trade_candidate_plans_symbol_trade_date,priority:2;type:date" json:"trade_date"`
	ReferencePrice float64   `gorm:"column:reference_price;not null;default:0" json:"reference_price"`
	EntryPrice     float64   `gorm:"column:entry_price;not null;default:0" json:"entry_price"`
	StopLoss       float64   `gorm:"column:stop_loss;not null;default:0" json:"stop_loss"`
	TakeProfit     float64   `gorm:"column:take_profit;not null;default:0" json:"take_profit"`
	PositionPct    float64   `gorm:"column:position_pct;not null;default:0" json:"position_pct"`
	Confidence     float64   `gorm:"column:confidence;not null;default:0" json:"confidence"`
	Status         string    `gorm:"column:status;not null;type:varchar(64)" json:"status"`
	Thesis         string    `gorm:"column:thesis;not null;type:text" json:"thesis"`
	RisksJson      []byte    `gorm:"column:risks_json;not null;type:json" json:"risks_json"`
	EvidenceJson   []byte    `gorm:"column:evidence_json;not null;type:json" json:"evidence_json"`
	PricingNote    string    `gorm:"column:pricing_note;not null;type:text" json:"pricing_note"`
	ConfigVersion  int64     `gorm:"column:config_version;not null" json:"config_version"`
	RuleVersion    string    `gorm:"column:rule_version;not null;type:varchar(64)" json:"rule_version"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;index:idx_trade_candidate_plans_document,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (*TradeCandidatePlan) TableName() string {
	return TableNameTradeCandidatePlan
}
