// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingReconciliationRun = "trading_reconciliation_runs"

// TradingReconciliationRun mapped from table <trading_reconciliation_runs>
type TradingReconciliationRun struct {
	ID                 int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RunKey             string     `gorm:"column:run_key;type:char(64);not null;uniqueIndex:uk_trading_reconciliation_runs_key,priority:1" json:"run_key"`
	RunType            string     `gorm:"column:run_type;type:varchar(32);not null" json:"run_type"`
	Status             string     `gorm:"column:status;type:varchar(32);not null;index:idx_trading_reconciliation_runs_status,priority:1;default:QUEUED" json:"status"`
	AccountID          string     `gorm:"column:account_id;type:varchar(128);not null;index:idx_trading_reconciliation_runs_account,priority:1" json:"account_id"`
	BridgeCursor       string     `gorm:"column:bridge_cursor;type:varchar(255);not null" json:"bridge_cursor"`
	SnapshotVersion    string     `gorm:"column:snapshot_version;type:varchar(128);not null" json:"snapshot_version"`
	OrderCount         int32      `gorm:"column:order_count;type:int;not null" json:"order_count"`
	FillCount          int32      `gorm:"column:fill_count;type:int;not null" json:"fill_count"`
	PositionCount      int32      `gorm:"column:position_count;type:int;not null" json:"position_count"`
	RepairedEventCount int32      `gorm:"column:repaired_event_count;type:int;not null" json:"repaired_event_count"`
	RepairedFillCount  int32      `gorm:"column:repaired_fill_count;type:int;not null" json:"repaired_fill_count"`
	DiffCount          int32      `gorm:"column:diff_count;type:int;not null" json:"diff_count"`
	RequestJSON        []byte     `gorm:"column:request_json;type:json;not null" json:"request_json"`
	SummaryJSON        []byte     `gorm:"column:summary_json;type:json;not null" json:"summary_json"`
	StartedAt          time.Time  `gorm:"column:started_at;type:timestamp(3);not null;index:idx_trading_reconciliation_runs_account,priority:2;index:idx_trading_reconciliation_runs_status,priority:2;default:CURRENT_TIMESTAMP(3)" json:"started_at"`
	FinishedAt         *time.Time `gorm:"column:finished_at;type:timestamp(3)" json:"finished_at"`
	ErrorCode          string     `gorm:"column:error_code;type:varchar(64);not null" json:"error_code"`
	ErrorMessage       string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	ConfigVersion      int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt          time.Time  `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt          time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingReconciliationRun's table name
func (*TradingReconciliationRun) TableName() string {
	return TableNameTradingReconciliationRun
}
