// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingReconciliationDiff = "trading_reconciliation_diffs"

// TradingReconciliationDiff mapped from table <trading_reconciliation_diffs>
type TradingReconciliationDiff struct {
	ID                  int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ReconciliationRunID int64      `gorm:"column:reconciliation_run_id;type:bigint;not null;index:idx_trading_reconciliation_diffs_run,priority:1" json:"reconciliation_run_id"`
	DiffType            string     `gorm:"column:diff_type;type:varchar(32);not null" json:"diff_type"`
	Severity            string     `gorm:"column:severity;type:varchar(16);not null;index:idx_trading_reconciliation_diffs_run,priority:2" json:"severity"`
	EntityType          string     `gorm:"column:entity_type;type:varchar(32);not null;index:idx_trading_reconciliation_diffs_entity,priority:1" json:"entity_type"`
	EntityKey           string     `gorm:"column:entity_key;type:varchar(255);not null;index:idx_trading_reconciliation_diffs_entity,priority:2" json:"entity_key"`
	FieldName           string     `gorm:"column:field_name;type:varchar(128);not null" json:"field_name"`
	LocalValueJSON      []byte     `gorm:"column:local_value_json;type:json;not null" json:"local_value_json"`
	ProviderValueJSON   []byte     `gorm:"column:provider_value_json;type:json;not null" json:"provider_value_json"`
	Resolution          string     `gorm:"column:resolution;type:varchar(32);not null;index:idx_trading_reconciliation_diffs_open,priority:1;default:OPEN" json:"resolution"`
	ResolutionMessage   string     `gorm:"column:resolution_message;type:text;not null" json:"resolution_message"`
	CreatedAt           time.Time  `gorm:"column:created_at;type:timestamp(3);not null;index:idx_trading_reconciliation_diffs_open,priority:2;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	ResolvedAt          *time.Time `gorm:"column:resolved_at;type:timestamp(3)" json:"resolved_at"`
}

// TableName TradingReconciliationDiff's table name
func (*TradingReconciliationDiff) TableName() string {
	return TableNameTradingReconciliationDiff
}
