// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingSkillDecision = "trading_skill_decisions"

// TradingSkillDecision mapped from table <trading_skill_decisions>
type TradingSkillDecision struct {
	ID                int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_trading_skill_decisions_cycle,priority:2;index:idx_trading_skill_decisions_intent,priority:2;index:idx_trading_skill_decisions_run,priority:3" json:"id"`
	DecisionKey       string    `gorm:"column:decision_key;type:char(64);not null;uniqueIndex:uk_trading_skill_decisions_key,priority:1" json:"decision_key"`
	TradingAgentRunID int64     `gorm:"column:trading_agent_run_id;type:bigint;not null;index:idx_trading_skill_decisions_run,priority:1" json:"trading_agent_run_id"`
	TradingIntentID   *int64    `gorm:"column:trading_intent_id;type:bigint;index:idx_trading_skill_decisions_intent,priority:1" json:"trading_intent_id"`
	PositionCycleID   *int64    `gorm:"column:position_cycle_id;type:bigint;index:idx_trading_skill_decisions_cycle,priority:1" json:"position_cycle_id"`
	Stage             string    `gorm:"column:stage;type:varchar(32);not null;index:idx_trading_skill_decisions_run,priority:2" json:"stage"`
	SkillName         string    `gorm:"column:skill_name;type:varchar(128);not null" json:"skill_name"`
	SkillVersion      string    `gorm:"column:skill_version;type:varchar(64);not null" json:"skill_version"`
	Decision          string    `gorm:"column:decision;type:varchar(32);not null" json:"decision"`
	Score             string    `gorm:"column:score;type:decimal(18,8);not null;default:0.00000000" json:"score"`
	Reason            string    `gorm:"column:reason;type:text;not null" json:"reason"`
	InputJSON         []byte    `gorm:"column:input_json;type:json;not null" json:"input_json"`
	OutputJSON        []byte    `gorm:"column:output_json;type:json;not null" json:"output_json"`
	EvaluatedAt       time.Time `gorm:"column:evaluated_at;type:timestamp(3);not null" json:"evaluated_at"`
	CreatedAt         time.Time `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TradingSkillDecision's table name
func (*TradingSkillDecision) TableName() string {
	return TableNameTradingSkillDecision
}
