// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingRuntimeControl = "trading_runtime_controls"

// TradingRuntimeControl mapped from table <trading_runtime_controls>
type TradingRuntimeControl struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ControlKey    string    `gorm:"column:control_key;type:varchar(64);not null;uniqueIndex:uk_trading_runtime_controls_key,priority:1" json:"control_key"`
	Enabled       bool      `gorm:"column:enabled;type:tinyint(1);not null;default:1" json:"enabled"`
	Reason        string    `gorm:"column:reason;type:text;not null" json:"reason"`
	ChangedBy     string    `gorm:"column:changed_by;type:varchar(128);not null" json:"changed_by"`
	ConfigVersion int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	ChangedAt     time.Time `gorm:"column:changed_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"changed_at"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingRuntimeControl's table name
func (*TradingRuntimeControl) TableName() string {
	return TableNameTradingRuntimeControl
}
