// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingBoardCapability = "trading_board_capabilities"

// TradingBoardCapability mapped from table <trading_board_capabilities>
type TradingBoardCapability struct {
	ID                    int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CapabilityKey         string     `gorm:"column:capability_key;type:char(64);not null;uniqueIndex:uk_trading_board_capabilities_key,priority:1" json:"capability_key"`
	Provider              string     `gorm:"column:provider;type:varchar(32);not null;uniqueIndex:uk_trading_board_capabilities_account,priority:1;default:EASTMONEY_GM" json:"provider"`
	Environment           string     `gorm:"column:environment;type:varchar(16);not null;uniqueIndex:uk_trading_board_capabilities_account,priority:2;default:SIMULATION" json:"environment"`
	AccountID             string     `gorm:"column:account_id;type:varchar(128);not null;uniqueIndex:uk_trading_board_capabilities_account,priority:3" json:"account_id"`
	BoardType             string     `gorm:"column:board_type;type:varchar(32);not null;uniqueIndex:uk_trading_board_capabilities_account,priority:4;index:idx_trading_board_capabilities_status,priority:2" json:"board_type"`
	AssetType             string     `gorm:"column:asset_type;type:varchar(32);not null;uniqueIndex:uk_trading_board_capabilities_account,priority:5" json:"asset_type"`
	BuyEnabled            bool       `gorm:"column:buy_enabled;type:tinyint(1);not null" json:"buy_enabled"`
	SellEnabled           bool       `gorm:"column:sell_enabled;type:tinyint(1);not null" json:"sell_enabled"`
	MinimumBuyVolume      int64      `gorm:"column:minimum_buy_volume;type:bigint;not null" json:"minimum_buy_volume"`
	BuyStep               int64      `gorm:"column:buy_step;type:bigint;not null" json:"buy_step"`
	MinimumSellVolume     int64      `gorm:"column:minimum_sell_volume;type:bigint;not null" json:"minimum_sell_volume"`
	SellStep              int64      `gorm:"column:sell_step;type:bigint;not null" json:"sell_step"`
	ResidualSellSupported bool       `gorm:"column:residual_sell_supported;type:tinyint(1);not null;default:1" json:"residual_sell_supported"`
	VerificationStatus    string     `gorm:"column:verification_status;type:varchar(32);not null;index:idx_trading_board_capabilities_status,priority:1;default:UNVERIFIED" json:"verification_status"`
	VerifiedAt            *time.Time `gorm:"column:verified_at;type:timestamp(3)" json:"verified_at"`
	EvidenceJSON          []byte     `gorm:"column:evidence_json;type:json;not null" json:"evidence_json"`
	TradingRuleVersion    string     `gorm:"column:trading_rule_version;type:varchar(64);not null" json:"trading_rule_version"`
	ConfigVersion         int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt             time.Time  `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt             time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingBoardCapability's table name
func (*TradingBoardCapability) TableName() string {
	return TableNameTradingBoardCapability
}
