// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingAgentRun = "trading_agent_runs"

// TradingAgentRun mapped from table <trading_agent_runs>
type TradingAgentRun struct {
	ID                  int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RunKey              string     `gorm:"column:run_key;type:char(64);not null;uniqueIndex:uk_trading_agent_runs_key,priority:1" json:"run_key"`
	TriggerType         string     `gorm:"column:trigger_type;type:varchar(32);not null;index:idx_trading_agent_runs_trigger,priority:1" json:"trigger_type"`
	Status              string     `gorm:"column:status;type:varchar(32);not null;index:idx_trading_agent_runs_claim,priority:1;index:idx_trading_agent_runs_status,priority:1;default:QUEUED" json:"status"`
	DecisionProvider    string     `gorm:"column:decision_provider;type:varchar(32);not null" json:"decision_provider"`
	StrategyName        string     `gorm:"column:strategy_name;type:varchar(128);not null;index:idx_trading_agent_runs_strategy,priority:1" json:"strategy_name"`
	StrategyVersion     string     `gorm:"column:strategy_version;type:varchar(64);not null" json:"strategy_version"`
	SchemaVersion       string     `gorm:"column:schema_version;type:varchar(64);not null" json:"schema_version"`
	PromptVersion       string     `gorm:"column:prompt_version;type:varchar(64);not null" json:"prompt_version"`
	ToolContractVersion string     `gorm:"column:tool_contract_version;type:varchar(64);not null" json:"tool_contract_version"`
	AsOfTime            time.Time  `gorm:"column:as_of_time;type:timestamp(3);not null;index:idx_trading_agent_runs_strategy,priority:2" json:"as_of_time"`
	InputCursor         string     `gorm:"column:input_cursor;type:varchar(255);not null" json:"input_cursor"`
	InputSnapshotHash   string     `gorm:"column:input_snapshot_hash;type:char(64);not null" json:"input_snapshot_hash"`
	RequestJSON         []byte     `gorm:"column:request_json;type:json;not null" json:"request_json"`
	RawOutputJSON       []byte     `gorm:"column:raw_output_json;type:json;not null" json:"raw_output_json"`
	CandidateCount      int32      `gorm:"column:candidate_count;type:int;not null" json:"candidate_count"`
	IntentCount         int32      `gorm:"column:intent_count;type:int;not null" json:"intent_count"`
	RejectedOutputCount int32      `gorm:"column:rejected_output_count;type:int;not null" json:"rejected_output_count"`
	DryRun              bool       `gorm:"column:dry_run;type:tinyint(1);not null" json:"dry_run"`
	WorkerID            string     `gorm:"column:worker_id;type:varchar(128);not null" json:"worker_id"`
	ClaimToken          string     `gorm:"column:claim_token;type:char(64);not null" json:"claim_token"`
	ClaimedAt           *time.Time `gorm:"column:claimed_at;type:timestamp(3)" json:"claimed_at"`
	ClaimDeadline       *time.Time `gorm:"column:claim_deadline;type:timestamp(3);index:idx_trading_agent_runs_claim,priority:2" json:"claim_deadline"`
	DecisionCompletedAt *time.Time `gorm:"column:decision_completed_at;type:timestamp(3)" json:"decision_completed_at"`
	QueuedAt            time.Time  `gorm:"column:queued_at;type:timestamp(3);not null;index:idx_trading_agent_runs_claim,priority:3;index:idx_trading_agent_runs_status,priority:2;default:CURRENT_TIMESTAMP(3)" json:"queued_at"`
	StartedAt           *time.Time `gorm:"column:started_at;type:timestamp(3)" json:"started_at"`
	FinishedAt          *time.Time `gorm:"column:finished_at;type:timestamp(3)" json:"finished_at"`
	ErrorCode           string     `gorm:"column:error_code;type:varchar(64);not null" json:"error_code"`
	ErrorMessage        string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	ConfigVersion       int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt           time.Time  `gorm:"column:created_at;type:timestamp(3);not null;index:idx_trading_agent_runs_trigger,priority:2;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt           time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingAgentRun's table name
func (*TradingAgentRun) TableName() string {
	return TableNameTradingAgentRun
}
