// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingPositionSnapshot = "trading_position_snapshots"

// TradingPositionSnapshot mapped from table <trading_position_snapshots>
type TradingPositionSnapshot struct {
	ID                int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AccountSnapshotID int64     `gorm:"column:account_snapshot_id;type:bigint;not null;uniqueIndex:uk_trading_position_snapshot,priority:1" json:"account_snapshot_id"`
	AccountID         string    `gorm:"column:account_id;type:varchar(128);not null;index:idx_trading_position_snapshots_account,priority:1" json:"account_id"`
	Symbol            string    `gorm:"column:symbol;type:varchar(32);not null" json:"symbol"`
	EastmoneySymbol   string    `gorm:"column:eastmoney_symbol;type:varchar(32);not null;uniqueIndex:uk_trading_position_snapshot,priority:2;index:idx_trading_position_snapshots_account,priority:2" json:"eastmoney_symbol"`
	PositionSide      string    `gorm:"column:position_side;type:varchar(16);not null;uniqueIndex:uk_trading_position_snapshot,priority:3;default:LONG" json:"position_side"`
	Volume            int64     `gorm:"column:volume;type:bigint;not null" json:"volume"`
	AvailableVolume   int64     `gorm:"column:available_volume;type:bigint;not null" json:"available_volume"`
	TodayVolume       int64     `gorm:"column:today_volume;type:bigint;not null" json:"today_volume"`
	Vwap              string    `gorm:"column:vwap;type:decimal(20,6);not null;default:0.000000" json:"vwap"`
	LastPrice         string    `gorm:"column:last_price;type:decimal(20,6);not null;default:0.000000" json:"last_price"`
	MarketValue       string    `gorm:"column:market_value;type:decimal(24,6);not null;default:0.000000" json:"market_value"`
	FloatingPnl       string    `gorm:"column:floating_pnl;type:decimal(24,6);not null;default:0.000000" json:"floating_pnl"`
	RawPayloadJSON    []byte    `gorm:"column:raw_payload_json;type:json;not null" json:"raw_payload_json"`
	CreatedAt         time.Time `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TradingPositionSnapshot's table name
func (*TradingPositionSnapshot) TableName() string {
	return TableNameTradingPositionSnapshot
}
