// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingIntent = "trading_intents"

// TradingIntent mapped from table <trading_intents>
type TradingIntent struct {
	ID                     int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_trading_intents_run,priority:2" json:"id"`
	TradingAgentRunID      int64      `gorm:"column:trading_agent_run_id;type:bigint;not null;index:idx_trading_intents_run,priority:1" json:"trading_agent_run_id"`
	IntentKey              string     `gorm:"column:intent_key;type:char(64);not null;uniqueIndex:uk_trading_intents_key,priority:1" json:"intent_key"`
	RecommendationEventID  *int64     `gorm:"column:recommendation_event_id;type:bigint;index:idx_trading_intents_event,priority:1" json:"recommendation_event_id"`
	CandidatePlanID        *int64     `gorm:"column:candidate_plan_id;type:bigint;index:idx_trading_intents_plan,priority:1" json:"candidate_plan_id"`
	PositionCycleID        *int64     `gorm:"column:position_cycle_id;type:bigint;index:idx_trading_intents_cycle,priority:1" json:"position_cycle_id"`
	Symbol                 string     `gorm:"column:symbol;type:varchar(32);not null;index:idx_trading_intents_symbol,priority:1" json:"symbol"`
	TSCode                 string     `gorm:"column:ts_code;type:varchar(16);not null" json:"ts_code"`
	Market                 string     `gorm:"column:market;type:varchar(16);not null" json:"market"`
	AssetType              string     `gorm:"column:asset_type;type:varchar(32);not null" json:"asset_type"`
	BoardType              string     `gorm:"column:board_type;type:varchar(32);not null;index:idx_trading_intents_board,priority:1;default:UNKNOWN" json:"board_type"`
	EastmoneySymbol        string     `gorm:"column:eastmoney_symbol;type:varchar(32);not null" json:"eastmoney_symbol"`
	TradeAction            string     `gorm:"column:trade_action;type:varchar(16);not null" json:"trade_action"`
	Status                 string     `gorm:"column:status;type:varchar(32);not null;index:idx_trading_intents_status,priority:1;default:PROPOSED" json:"status"`
	ExecutionStatus        string     `gorm:"column:execution_status;type:varchar(32);not null;index:idx_trading_intents_execution,priority:1;default:PENDING" json:"execution_status"`
	ExecutionAttemptCount  int32      `gorm:"column:execution_attempt_count;type:int;not null" json:"execution_attempt_count"`
	NextExecutionAt        *time.Time `gorm:"column:next_execution_at;type:timestamp(3);index:idx_trading_intents_execution,priority:2" json:"next_execution_at"`
	ExecutionClaimToken    string     `gorm:"column:execution_claim_token;type:char(64);not null" json:"execution_claim_token"`
	ExecutionClaimedBy     string     `gorm:"column:execution_claimed_by;type:varchar(128);not null" json:"execution_claimed_by"`
	ExecutionClaimedAt     *time.Time `gorm:"column:execution_claimed_at;type:timestamp(3)" json:"execution_claimed_at"`
	ExecutionClaimDeadline *time.Time `gorm:"column:execution_claim_deadline;type:timestamp(3);index:idx_trading_intents_execution,priority:3" json:"execution_claim_deadline"`
	ExecutedAt             *time.Time `gorm:"column:executed_at;type:timestamp(3)" json:"executed_at"`
	ProposedOrderType      string     `gorm:"column:proposed_order_type;type:varchar(16);not null;default:LIMIT" json:"proposed_order_type"`
	ProposedLimitPrice     *string    `gorm:"column:proposed_limit_price;type:decimal(20,6)" json:"proposed_limit_price"`
	ProposedPositionRatio  *string    `gorm:"column:proposed_position_ratio;type:decimal(18,8)" json:"proposed_position_ratio"`
	ProposedVolume         *int64     `gorm:"column:proposed_volume;type:bigint" json:"proposed_volume"`
	Confidence             string     `gorm:"column:confidence;type:decimal(18,8);not null;default:0.00000000" json:"confidence"`
	ValidFrom              time.Time  `gorm:"column:valid_from;type:timestamp(3);not null" json:"valid_from"`
	ValidUntil             time.Time  `gorm:"column:valid_until;type:timestamp(3);not null;index:idx_trading_intents_status,priority:2" json:"valid_until"`
	Reason                 string     `gorm:"column:reason;type:text;not null" json:"reason"`
	EvidenceRefsJSON       []byte     `gorm:"column:evidence_refs_json;type:json;not null" json:"evidence_refs_json"`
	RawIntentJSON          []byte     `gorm:"column:raw_intent_json;type:json;not null" json:"raw_intent_json"`
	RejectionCode          string     `gorm:"column:rejection_code;type:varchar(64);not null" json:"rejection_code"`
	RejectionMessage       string     `gorm:"column:rejection_message;type:text;not null" json:"rejection_message"`
	StrategyVersion        string     `gorm:"column:strategy_version;type:varchar(64);not null" json:"strategy_version"`
	ConfigVersion          int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt              time.Time  `gorm:"column:created_at;type:timestamp(3);not null;index:idx_trading_intents_board,priority:2;index:idx_trading_intents_symbol,priority:2;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt              time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingIntent's table name
func (*TradingIntent) TableName() string {
	return TableNameTradingIntent
}
