// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingPositionCycle = "trading_position_cycles"

// TradingPositionCycle mapped from table <trading_position_cycles>
type TradingPositionCycle struct {
	ID                          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CycleKey                    string     `gorm:"column:cycle_key;type:char(64);not null;uniqueIndex:uk_trading_position_cycles_key,priority:1" json:"cycle_key"`
	Environment                 string     `gorm:"column:environment;type:varchar(16);not null;default:SIMULATION" json:"environment"`
	Provider                    string     `gorm:"column:provider;type:varchar(32);not null;default:EASTMONEY_GM" json:"provider"`
	AccountID                   string     `gorm:"column:account_id;type:varchar(128);not null;index:idx_trading_position_cycles_open,priority:1" json:"account_id"`
	Symbol                      string     `gorm:"column:symbol;type:varchar(16);not null" json:"symbol"`
	TSCode                      string     `gorm:"column:ts_code;type:varchar(16);not null" json:"ts_code"`
	EastmoneySymbol             string     `gorm:"column:eastmoney_symbol;type:varchar(32);not null;index:idx_trading_position_cycles_open,priority:3" json:"eastmoney_symbol"`
	Market                      string     `gorm:"column:market;type:varchar(16);not null" json:"market"`
	AssetType                   string     `gorm:"column:asset_type;type:varchar(32);not null" json:"asset_type"`
	BoardType                   string     `gorm:"column:board_type;type:varchar(32);not null" json:"board_type"`
	Status                      string     `gorm:"column:status;type:varchar(32);not null;index:idx_trading_position_cycles_open,priority:2;index:idx_trading_position_cycles_sellable,priority:1;default:OPEN" json:"status"`
	SourceRecommendationEventID *int64     `gorm:"column:source_recommendation_event_id;type:bigint;index:idx_trading_position_cycles_event,priority:1" json:"source_recommendation_event_id"`
	SourceBuyIntentID           *int64     `gorm:"column:source_buy_intent_id;type:bigint;index:fk_trading_position_cycles_buy_intent,priority:1" json:"source_buy_intent_id"`
	EntryOrderID                *int64     `gorm:"column:entry_order_id;type:bigint;index:fk_trading_position_cycles_entry_order,priority:1" json:"entry_order_id"`
	ExitOrderID                 *int64     `gorm:"column:exit_order_id;type:bigint;index:fk_trading_position_cycles_exit_order,priority:1" json:"exit_order_id"`
	EntryTradeDate              time.Time  `gorm:"column:entry_trade_date;type:date;not null" json:"entry_trade_date"`
	SellableTradeDate           time.Time  `gorm:"column:sellable_trade_date;type:date;not null;index:idx_trading_position_cycles_sellable,priority:2" json:"sellable_trade_date"`
	EntryPrice                  string     `gorm:"column:entry_price;type:decimal(20,6);not null" json:"entry_price"`
	InitialVolume               int64      `gorm:"column:initial_volume;type:bigint;not null" json:"initial_volume"`
	CurrentVolume               int64      `gorm:"column:current_volume;type:bigint;not null" json:"current_volume"`
	AvailableVolume             int64      `gorm:"column:available_volume;type:bigint;not null" json:"available_volume"`
	StopLossPrice               string     `gorm:"column:stop_loss_price;type:decimal(20,6);not null" json:"stop_loss_price"`
	TakeProfitPrice             string     `gorm:"column:take_profit_price;type:decimal(20,6);not null" json:"take_profit_price"`
	MaxHoldingTradeDays         int32      `gorm:"column:max_holding_trade_days;type:int;not null" json:"max_holding_trade_days"`
	HoldingTradeDays            int32      `gorm:"column:holding_trade_days;type:int;not null" json:"holding_trade_days"`
	ExitReason                  string     `gorm:"column:exit_reason;type:varchar(64);not null" json:"exit_reason"`
	OpenedAt                    time.Time  `gorm:"column:opened_at;type:timestamp(3);not null" json:"opened_at"`
	ClosedAt                    *time.Time `gorm:"column:closed_at;type:timestamp(3)" json:"closed_at"`
	LastEvaluatedAt             *time.Time `gorm:"column:last_evaluated_at;type:timestamp(3);index:idx_trading_position_cycles_sellable,priority:3" json:"last_evaluated_at"`
	StrategyVersion             string     `gorm:"column:strategy_version;type:varchar(64);not null" json:"strategy_version"`
	RuleVersion                 string     `gorm:"column:rule_version;type:varchar(64);not null" json:"rule_version"`
	ConfigVersion               int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt                   time.Time  `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt                   time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingPositionCycle's table name
func (*TradingPositionCycle) TableName() string {
	return TableNameTradingPositionCycle
}
