// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingOrder = "trading_orders"

// TradingOrder mapped from table <trading_orders>
type TradingOrder struct {
	ID                        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TradingIntentID           int64      `gorm:"column:trading_intent_id;type:bigint;not null;index:idx_trading_orders_intent,priority:1" json:"trading_intent_id"`
	ClientOrderID             string     `gorm:"column:client_order_id;type:varchar(64);not null;uniqueIndex:uk_trading_orders_client,priority:1" json:"client_order_id"`
	IdempotencyKey            string     `gorm:"column:idempotency_key;type:char(64);not null;uniqueIndex:uk_trading_orders_idempotency,priority:1" json:"idempotency_key"`
	DispatchSeq               int32      `gorm:"column:dispatch_seq;type:int;not null;index:idx_trading_orders_intent,priority:2;default:1" json:"dispatch_seq"`
	Environment               string     `gorm:"column:environment;type:varchar(16);not null;default:SIMULATION" json:"environment"`
	Provider                  string     `gorm:"column:provider;type:varchar(32);not null;uniqueIndex:uk_trading_orders_provider_cl_ord,priority:1;default:EASTMONEY_GM" json:"provider"`
	AccountID                 string     `gorm:"column:account_id;type:varchar(128);not null;uniqueIndex:uk_trading_orders_provider_cl_ord,priority:2;index:idx_trading_orders_account,priority:1" json:"account_id"`
	StrategyID                string     `gorm:"column:strategy_id;type:varchar(128);not null" json:"strategy_id"`
	Symbol                    string     `gorm:"column:symbol;type:varchar(32);not null;index:idx_trading_orders_symbol,priority:1" json:"symbol"`
	EastmoneySymbol           string     `gorm:"column:eastmoney_symbol;type:varchar(32);not null" json:"eastmoney_symbol"`
	Side                      string     `gorm:"column:side;type:varchar(16);not null" json:"side"`
	PositionEffect            string     `gorm:"column:position_effect;type:varchar(16);not null" json:"position_effect"`
	OrderType                 string     `gorm:"column:order_type;type:varchar(16);not null" json:"order_type"`
	LimitPrice                *string    `gorm:"column:limit_price;type:decimal(20,6)" json:"limit_price"`
	Volume                    int64      `gorm:"column:volume;type:bigint;not null" json:"volume"`
	Status                    string     `gorm:"column:status;type:varchar(32);not null;index:idx_trading_orders_status,priority:1;default:DISPATCH_PENDING" json:"status"`
	ProviderStatus            string     `gorm:"column:provider_status;type:varchar(32);not null" json:"provider_status"`
	ClOrdID                   string     `gorm:"column:cl_ord_id;type:varchar(128);uniqueIndex:uk_trading_orders_provider_cl_ord,priority:3" json:"cl_ord_id"`
	OrderID                   string     `gorm:"column:order_id;type:varchar(128)" json:"order_id"`
	FilledVolume              int64      `gorm:"column:filled_volume;type:bigint;not null" json:"filled_volume"`
	FilledVwap                *string    `gorm:"column:filled_vwap;type:decimal(20,6)" json:"filled_vwap"`
	FilledAmount              string     `gorm:"column:filled_amount;type:decimal(24,6);not null;default:0.000000" json:"filled_amount"`
	FilledCommission          string     `gorm:"column:filled_commission;type:decimal(20,6);not null;default:0.000000" json:"filled_commission"`
	ValidUntil                time.Time  `gorm:"column:valid_until;type:timestamp(3);not null" json:"valid_until"`
	RiskSnapshotHash          string     `gorm:"column:risk_snapshot_hash;type:char(64);not null" json:"risk_snapshot_hash"`
	DispatchAttemptCount      int32      `gorm:"column:dispatch_attempt_count;type:int;not null" json:"dispatch_attempt_count"`
	NextDispatchAt            *time.Time `gorm:"column:next_dispatch_at;type:timestamp(3);index:idx_trading_orders_status,priority:2" json:"next_dispatch_at"`
	SubmittedAt               *time.Time `gorm:"column:submitted_at;type:timestamp(3)" json:"submitted_at"`
	LastEventAt               *time.Time `gorm:"column:last_event_at;type:timestamp(3)" json:"last_event_at"`
	FinishedAt                *time.Time `gorm:"column:finished_at;type:timestamp(3)" json:"finished_at"`
	ErrorCode                 string     `gorm:"column:error_code;type:varchar(64);not null" json:"error_code"`
	ErrorMessage              string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	RequestJSON               []byte     `gorm:"column:request_json;type:json;not null" json:"request_json"`
	LatestProviderPayloadJSON []byte     `gorm:"column:latest_provider_payload_json;type:json;not null" json:"latest_provider_payload_json"`
	RiskVersion               string     `gorm:"column:risk_version;type:varchar(64);not null" json:"risk_version"`
	ConfigVersion             int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt                 time.Time  `gorm:"column:created_at;type:timestamp(3);not null;index:idx_trading_orders_account,priority:2;index:idx_trading_orders_symbol,priority:2;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt                 time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingOrder's table name
func (*TradingOrder) TableName() string {
	return TableNameTradingOrder
}
