// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingRiskCheck = "trading_risk_checks"

// TradingRiskCheck mapped from table <trading_risk_checks>
type TradingRiskCheck struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TradingIntentID int64     `gorm:"column:trading_intent_id;type:bigint;not null;uniqueIndex:uk_trading_risk_check,priority:1" json:"trading_intent_id"`
	EvaluationNo    int32     `gorm:"column:evaluation_no;type:int;not null;uniqueIndex:uk_trading_risk_check,priority:2;default:1" json:"evaluation_no"`
	CheckCode       string    `gorm:"column:check_code;type:varchar(64);not null;uniqueIndex:uk_trading_risk_check,priority:3;index:idx_trading_risk_checks_result,priority:2" json:"check_code"`
	CheckOrder      int32     `gorm:"column:check_order;type:int;not null" json:"check_order"`
	Passed          bool      `gorm:"column:passed;type:tinyint(1);not null;index:idx_trading_risk_checks_result,priority:1" json:"passed"`
	Decision        string    `gorm:"column:decision;type:varchar(32);not null" json:"decision"`
	ReasonMessage   string    `gorm:"column:reason_message;type:text;not null" json:"reason_message"`
	ObservedJSON    []byte    `gorm:"column:observed_json;type:json;not null" json:"observed_json"`
	LimitJSON       []byte    `gorm:"column:limit_json;type:json;not null" json:"limit_json"`
	RiskVersion     string    `gorm:"column:risk_version;type:varchar(64);not null" json:"risk_version"`
	ConfigVersion   int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CheckedAt       time.Time `gorm:"column:checked_at;type:timestamp(3);not null;index:idx_trading_risk_checks_result,priority:3;default:CURRENT_TIMESTAMP(3)" json:"checked_at"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName TradingRiskCheck's table name
func (*TradingRiskCheck) TableName() string {
	return TableNameTradingRiskCheck
}
