// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradingDailySession = "trading_daily_sessions"

// TradingDailySession mapped from table <trading_daily_sessions>
type TradingDailySession struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SessionKey      string     `gorm:"column:session_key;type:char(64);not null;uniqueIndex:uk_trading_daily_sessions_key,priority:1" json:"session_key"`
	Environment     string     `gorm:"column:environment;type:varchar(16);not null;default:SIMULATION" json:"environment"`
	Provider        string     `gorm:"column:provider;type:varchar(32);not null;uniqueIndex:uk_trading_daily_sessions_account_date,priority:1;default:EASTMONEY_GM" json:"provider"`
	AccountID       string     `gorm:"column:account_id;type:varchar(128);not null;uniqueIndex:uk_trading_daily_sessions_account_date,priority:2" json:"account_id"`
	TradeDate       time.Time  `gorm:"column:trade_date;type:date;not null;uniqueIndex:uk_trading_daily_sessions_account_date,priority:3;index:idx_trading_daily_sessions_status,priority:2" json:"trade_date"`
	Status          string     `gorm:"column:status;type:varchar(32);not null;index:idx_trading_daily_sessions_status,priority:1;default:PENDING" json:"status"`
	PreflightStatus string     `gorm:"column:preflight_status;type:varchar(32);not null;default:PENDING" json:"preflight_status"`
	AuthState       string     `gorm:"column:auth_state;type:varchar(32);not null;default:UNKNOWN" json:"auth_state"`
	BridgeState     string     `gorm:"column:bridge_state;type:varchar(32);not null;default:UNKNOWN" json:"bridge_state"`
	DecisionRunID   *int64     `gorm:"column:decision_run_id;type:bigint;index:fk_trading_daily_sessions_run,priority:1" json:"decision_run_id"`
	OpenedAt        *time.Time `gorm:"column:opened_at;type:timestamp(3)" json:"opened_at"`
	ClosedAt        *time.Time `gorm:"column:closed_at;type:timestamp(3)" json:"closed_at"`
	PreflightJSON   []byte     `gorm:"column:preflight_json;type:json;not null" json:"preflight_json"`
	SummaryJSON     []byte     `gorm:"column:summary_json;type:json;not null" json:"summary_json"`
	ErrorCode       string     `gorm:"column:error_code;type:varchar(64);not null" json:"error_code"`
	ErrorMessage    string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	ConfigVersion   int64      `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	CreatedAt       time.Time  `gorm:"column:created_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt       time.Time  `gorm:"column:updated_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName TradingDailySession's table name
func (*TradingDailySession) TableName() string {
	return TableNameTradingDailySession
}
