// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameTradeCandidatePlan = "trade_candidate_plans"

// TradeCandidatePlan mapped from table <trade_candidate_plans>
type TradeCandidatePlan struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	DocumentID     int64     `gorm:"column:document_id;type:bigint;not null;index:idx_trade_candidate_plans_document,priority:1" json:"document_id"`
	ParseRunID     int64     `gorm:"column:parse_run_id;type:bigint;not null;index:fk_trade_candidate_plans_parse_run,priority:1" json:"parse_run_id"`
	Analyst        string    `gorm:"column:analyst;type:varchar(128);not null" json:"analyst"`
	Institution    string    `gorm:"column:institution;type:varchar(128);not null" json:"institution"`
	Symbol         string    `gorm:"column:symbol;type:varchar(32);not null;index:idx_trade_candidate_plans_symbol_trade_date,priority:1" json:"symbol"`
	AssetType      string    `gorm:"column:asset_type;type:varchar(32);not null" json:"asset_type"`
	Market         string    `gorm:"column:market;type:varchar(32);not null" json:"market"`
	Strategy       string    `gorm:"column:strategy;type:varchar(64);not null" json:"strategy"`
	Direction      string    `gorm:"column:direction;type:varchar(16);not null" json:"direction"`
	TradeDate      time.Time `gorm:"column:trade_date;type:date;not null;index:idx_trade_candidate_plans_symbol_trade_date,priority:2" json:"trade_date"`
	ReferencePrice float64   `gorm:"column:reference_price;type:double;not null" json:"reference_price"`
	EntryPrice     float64   `gorm:"column:entry_price;type:double;not null" json:"entry_price"`
	StopLoss       float64   `gorm:"column:stop_loss;type:double;not null" json:"stop_loss"`
	TakeProfit     float64   `gorm:"column:take_profit;type:double;not null" json:"take_profit"`
	PositionPct    float64   `gorm:"column:position_pct;type:double;not null" json:"position_pct"`
	Confidence     float64   `gorm:"column:confidence;type:double;not null" json:"confidence"`
	Status         string    `gorm:"column:status;type:varchar(64);not null" json:"status"`
	Thesis         string    `gorm:"column:thesis;type:text;not null" json:"thesis"`
	RisksJSON      []byte    `gorm:"column:risks_json;type:json;not null" json:"risks_json"`
	EvidenceJSON   []byte    `gorm:"column:evidence_json;type:json;not null" json:"evidence_json"`
	PricingNote    string    `gorm:"column:pricing_note;type:text;not null" json:"pricing_note"`
	ConfigVersion  int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	RuleVersion    string    `gorm:"column:rule_version;type:varchar(64);not null" json:"rule_version"`
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_trade_candidate_plans_document,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TradeCandidatePlan's table name
func (*TradeCandidatePlan) TableName() string {
	return TableNameTradeCandidatePlan
}
