// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameUntrackableTarget = "untrackable_targets"

// UntrackableTarget mapped from table <untrackable_targets>
type UntrackableTarget struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ResolutionRunID  int64     `gorm:"column:resolution_run_id;type:bigint;not null;index:idx_untrackable_run,priority:1" json:"resolution_run_id"`
	DocumentID       int64     `gorm:"column:document_id;type:bigint;not null;index:idx_untrackable_document_active,priority:1" json:"document_id"`
	ParseRunID       *int64    `gorm:"column:parse_run_id;type:bigint;index:idx_untrackable_parse_run,priority:1" json:"parse_run_id"`
	RawTarget        string    `gorm:"column:raw_target;type:varchar(255);not null" json:"raw_target"`
	NormalizedTarget string    `gorm:"column:normalized_target;type:varchar(255);not null;index:idx_untrackable_normalized,priority:1" json:"normalized_target"`
	TargetKind       string    `gorm:"column:target_kind;type:varchar(32);not null;index:idx_untrackable_kind_reason,priority:1" json:"target_kind"`
	ReasonCode       string    `gorm:"column:reason_code;type:varchar(64);not null;index:idx_untrackable_kind_reason,priority:2" json:"reason_code"`
	ReasonMessage    string    `gorm:"column:reason_message;type:text;not null" json:"reason_message"`
	Source           string    `gorm:"column:source;type:varchar(32);not null" json:"source"`
	EvidenceJSON     []byte    `gorm:"column:evidence_json;type:json;not null" json:"evidence_json"`
	CandidatesJSON   []byte    `gorm:"column:candidates_json;type:json;not null" json:"candidates_json"`
	ConfigVersion    int64     `gorm:"column:config_version;type:bigint;not null" json:"config_version"`
	IsActive         bool      `gorm:"column:is_active;type:tinyint(1);not null;index:idx_untrackable_document_active,priority:2;default:1" json:"is_active"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_untrackable_document_active,priority:3;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UntrackableTarget's table name
func (*UntrackableTarget) TableName() string {
	return TableNameUntrackableTarget
}
