// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePlan = `-- name: ApprovePlan :one
UPDATE plans
SET status = 'APPROVED',
    approved_by = $2,
    approved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, signal_id, document_id, symbol, strategy, trade_date, direction, entry_price, stop_loss, take_profit, invalidation_price, position_pct, status, rationale, config_version, rule_version, market_snapshot_id, approved_by, approved_at, created_at, updated_at
`

type ApprovePlanParams struct {
	ID         int64  `json:"id"`
	ApprovedBy string `json:"approved_by"`
}

func (q *Queries) ApprovePlan(ctx context.Context, arg ApprovePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, approvePlan, arg.ID, arg.ApprovedBy)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SignalID,
		&i.DocumentID,
		&i.Symbol,
		&i.Strategy,
		&i.TradeDate,
		&i.Direction,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.InvalidationPrice,
		&i.PositionPct,
		&i.Status,
		&i.Rationale,
		&i.ConfigVersion,
		&i.RuleVersion,
		&i.MarketSnapshotID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, object_key, status, config_version, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceName,
		&i.Author,
		&i.Institution,
		&i.Title,
		&i.FileName,
		&i.Extension,
		&i.ContentType,
		&i.Sha256,
		&i.ObjectKey,
		&i.Status,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySHA = `-- name: GetDocumentBySHA :one
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, object_key, status, config_version, created_at, updated_at
FROM documents
WHERE sha256 = $1
`

func (q *Queries) GetDocumentBySHA(ctx context.Context, sha256 string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySHA, sha256)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceName,
		&i.Author,
		&i.Institution,
		&i.Title,
		&i.FileName,
		&i.Extension,
		&i.ContentType,
		&i.Sha256,
		&i.ObjectKey,
		&i.Status,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestParseRunByDocumentID = `-- name: GetLatestParseRunByDocumentID :one
SELECT id, document_id, status, parser_name, parser_version, requires_ocr, error_message, page_count, text_density, content_text, cleaned_text, sections_json, chunks_json, tables_json, raw_metadata_json, created_at, updated_at
FROM parse_runs
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestParseRunByDocumentID(ctx context.Context, documentID int64) (ParseRun, error) {
	row := q.db.QueryRow(ctx, getLatestParseRunByDocumentID, documentID)
	var i ParseRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.ParserName,
		&i.ParserVersion,
		&i.RequiresOcr,
		&i.ErrorMessage,
		&i.PageCount,
		&i.TextDensity,
		&i.ContentText,
		&i.CleanedText,
		&i.SectionsJson,
		&i.ChunksJson,
		&i.TablesJson,
		&i.RawMetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketSnapshotBySymbolDate = `-- name: GetMarketSnapshotBySymbolDate :one
SELECT id, symbol, trade_date, provider, open, high, low, close, volume, turnover, atr, prev_close, benchmark_return_pct, raw_object_key, config_version, created_at
FROM market_snapshots
WHERE symbol = $1 AND trade_date = $2
`

type GetMarketSnapshotBySymbolDateParams struct {
	Symbol    string      `json:"symbol"`
	TradeDate pgtype.Date `json:"trade_date"`
}

func (q *Queries) GetMarketSnapshotBySymbolDate(ctx context.Context, arg GetMarketSnapshotBySymbolDateParams) (MarketSnapshot, error) {
	row := q.db.QueryRow(ctx, getMarketSnapshotBySymbolDate, arg.Symbol, arg.TradeDate)
	var i MarketSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.TradeDate,
		&i.Provider,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.Turnover,
		&i.Atr,
		&i.PrevClose,
		&i.BenchmarkReturnPct,
		&i.RawObjectKey,
		&i.ConfigVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, signal_id, document_id, symbol, strategy, trade_date, direction, entry_price, stop_loss, take_profit, invalidation_price, position_pct, status, rationale, config_version, rule_version, market_snapshot_id, approved_by, approved_at, created_at, updated_at
FROM plans
WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SignalID,
		&i.DocumentID,
		&i.Symbol,
		&i.Strategy,
		&i.TradeDate,
		&i.Direction,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.InvalidationPrice,
		&i.PositionPct,
		&i.Status,
		&i.Rationale,
		&i.ConfigVersion,
		&i.RuleVersion,
		&i.MarketSnapshotID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignalByID = `-- name: GetSignalByID :one
SELECT id, document_id, parse_run_id, expert_name, expert_org, symbol, asset_type, market, sentiment, thesis, evidence_json, risks_json, confidence, config_version, rule_version, signal_date, created_at
FROM signals
WHERE id = $1
`

func (q *Queries) GetSignalByID(ctx context.Context, id int64) (Signal, error) {
	row := q.db.QueryRow(ctx, getSignalByID, id)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParseRunID,
		&i.ExpertName,
		&i.ExpertOrg,
		&i.Symbol,
		&i.AssetType,
		&i.Market,
		&i.Sentiment,
		&i.Thesis,
		&i.EvidenceJson,
		&i.RisksJson,
		&i.Confidence,
		&i.ConfigVersion,
		&i.RuleVersion,
		&i.SignalDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertConfigSnapshot = `-- name: InsertConfigSnapshot :one
INSERT INTO config_snapshots (
    config_version,
    source,
    sha256,
    raw_json
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, config_version, source, sha256, raw_json, created_at
`

type InsertConfigSnapshotParams struct {
	ConfigVersion int64  `json:"config_version"`
	Source        string `json:"source"`
	Sha256        string `json:"sha256"`
	RawJson       []byte `json:"raw_json"`
}

func (q *Queries) InsertConfigSnapshot(ctx context.Context, arg InsertConfigSnapshotParams) (ConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, insertConfigSnapshot,
		arg.ConfigVersion,
		arg.Source,
		arg.Sha256,
		arg.RawJson,
	)
	var i ConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.ConfigVersion,
		&i.Source,
		&i.Sha256,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (
    source_type,
    source_name,
    author,
    institution,
    title,
    file_name,
    extension,
    content_type,
    sha256,
    object_key,
    status,
    config_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, object_key, status, config_version, created_at, updated_at
`

type InsertDocumentParams struct {
	SourceType    string `json:"source_type"`
	SourceName    string `json:"source_name"`
	Author        string `json:"author"`
	Institution   string `json:"institution"`
	Title         string `json:"title"`
	FileName      string `json:"file_name"`
	Extension     string `json:"extension"`
	ContentType   string `json:"content_type"`
	Sha256        string `json:"sha256"`
	ObjectKey     string `json:"object_key"`
	Status        string `json:"status"`
	ConfigVersion int64  `json:"config_version"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.SourceType,
		arg.SourceName,
		arg.Author,
		arg.Institution,
		arg.Title,
		arg.FileName,
		arg.Extension,
		arg.ContentType,
		arg.Sha256,
		arg.ObjectKey,
		arg.Status,
		arg.ConfigVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceName,
		&i.Author,
		&i.Institution,
		&i.Title,
		&i.FileName,
		&i.Extension,
		&i.ContentType,
		&i.Sha256,
		&i.ObjectKey,
		&i.Status,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvaluation = `-- name: InsertEvaluation :one
INSERT INTO evaluations (
    plan_id,
    trade_date,
    status,
    entry_price,
    exit_price,
    close_price,
    pnl_pct,
    mfe_pct,
    mae_pct,
    benchmark_return_pct,
    excess_return_pct,
    reason,
    data_quality_flag,
    config_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, plan_id, trade_date, status, entry_price, exit_price, close_price, pnl_pct, mfe_pct, mae_pct, benchmark_return_pct, excess_return_pct, reason, data_quality_flag, config_version, created_at
`

type InsertEvaluationParams struct {
	PlanID             int64       `json:"plan_id"`
	TradeDate          pgtype.Date `json:"trade_date"`
	Status             string      `json:"status"`
	EntryPrice         float64     `json:"entry_price"`
	ExitPrice          float64     `json:"exit_price"`
	ClosePrice         float64     `json:"close_price"`
	PnlPct             float64     `json:"pnl_pct"`
	MfePct             float64     `json:"mfe_pct"`
	MaePct             float64     `json:"mae_pct"`
	BenchmarkReturnPct float64     `json:"benchmark_return_pct"`
	ExcessReturnPct    float64     `json:"excess_return_pct"`
	Reason             string      `json:"reason"`
	DataQualityFlag    string      `json:"data_quality_flag"`
	ConfigVersion      int64       `json:"config_version"`
}

func (q *Queries) InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (Evaluation, error) {
	row := q.db.QueryRow(ctx, insertEvaluation,
		arg.PlanID,
		arg.TradeDate,
		arg.Status,
		arg.EntryPrice,
		arg.ExitPrice,
		arg.ClosePrice,
		arg.PnlPct,
		arg.MfePct,
		arg.MaePct,
		arg.BenchmarkReturnPct,
		arg.ExcessReturnPct,
		arg.Reason,
		arg.DataQualityFlag,
		arg.ConfigVersion,
	)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.TradeDate,
		&i.Status,
		&i.EntryPrice,
		&i.ExitPrice,
		&i.ClosePrice,
		&i.PnlPct,
		&i.MfePct,
		&i.MaePct,
		&i.BenchmarkReturnPct,
		&i.ExcessReturnPct,
		&i.Reason,
		&i.DataQualityFlag,
		&i.ConfigVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertMarketSnapshot = `-- name: InsertMarketSnapshot :one
INSERT INTO market_snapshots (
    symbol,
    trade_date,
    provider,
    open,
    high,
    low,
    close,
    volume,
    turnover,
    atr,
    prev_close,
    benchmark_return_pct,
    raw_object_key,
    config_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (symbol, trade_date)
DO UPDATE SET
    provider = EXCLUDED.provider,
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    turnover = EXCLUDED.turnover,
    atr = EXCLUDED.atr,
    prev_close = EXCLUDED.prev_close,
    benchmark_return_pct = EXCLUDED.benchmark_return_pct,
    raw_object_key = EXCLUDED.raw_object_key,
    config_version = EXCLUDED.config_version
RETURNING id, symbol, trade_date, provider, open, high, low, close, volume, turnover, atr, prev_close, benchmark_return_pct, raw_object_key, config_version, created_at
`

type InsertMarketSnapshotParams struct {
	Symbol             string      `json:"symbol"`
	TradeDate          pgtype.Date `json:"trade_date"`
	Provider           string      `json:"provider"`
	Open               float64     `json:"open"`
	High               float64     `json:"high"`
	Low                float64     `json:"low"`
	Close              float64     `json:"close"`
	Volume             float64     `json:"volume"`
	Turnover           float64     `json:"turnover"`
	Atr                float64     `json:"atr"`
	PrevClose          float64     `json:"prev_close"`
	BenchmarkReturnPct float64     `json:"benchmark_return_pct"`
	RawObjectKey       string      `json:"raw_object_key"`
	ConfigVersion      int64       `json:"config_version"`
}

func (q *Queries) InsertMarketSnapshot(ctx context.Context, arg InsertMarketSnapshotParams) (MarketSnapshot, error) {
	row := q.db.QueryRow(ctx, insertMarketSnapshot,
		arg.Symbol,
		arg.TradeDate,
		arg.Provider,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.Turnover,
		arg.Atr,
		arg.PrevClose,
		arg.BenchmarkReturnPct,
		arg.RawObjectKey,
		arg.ConfigVersion,
	)
	var i MarketSnapshot
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.TradeDate,
		&i.Provider,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.Turnover,
		&i.Atr,
		&i.PrevClose,
		&i.BenchmarkReturnPct,
		&i.RawObjectKey,
		&i.ConfigVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertParseRun = `-- name: InsertParseRun :one
INSERT INTO parse_runs (
    document_id,
    status,
    parser_name,
    parser_version,
    requires_ocr,
    error_message,
    page_count,
    text_density,
    content_text,
    cleaned_text,
    sections_json,
    chunks_json,
    tables_json,
    raw_metadata_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, document_id, status, parser_name, parser_version, requires_ocr, error_message, page_count, text_density, content_text, cleaned_text, sections_json, chunks_json, tables_json, raw_metadata_json, created_at, updated_at
`

type InsertParseRunParams struct {
	DocumentID      int64   `json:"document_id"`
	Status          string  `json:"status"`
	ParserName      string  `json:"parser_name"`
	ParserVersion   string  `json:"parser_version"`
	RequiresOcr     bool    `json:"requires_ocr"`
	ErrorMessage    string  `json:"error_message"`
	PageCount       int32   `json:"page_count"`
	TextDensity     float64 `json:"text_density"`
	ContentText     string  `json:"content_text"`
	CleanedText     string  `json:"cleaned_text"`
	SectionsJson    []byte  `json:"sections_json"`
	ChunksJson      []byte  `json:"chunks_json"`
	TablesJson      []byte  `json:"tables_json"`
	RawMetadataJson []byte  `json:"raw_metadata_json"`
}

func (q *Queries) InsertParseRun(ctx context.Context, arg InsertParseRunParams) (ParseRun, error) {
	row := q.db.QueryRow(ctx, insertParseRun,
		arg.DocumentID,
		arg.Status,
		arg.ParserName,
		arg.ParserVersion,
		arg.RequiresOcr,
		arg.ErrorMessage,
		arg.PageCount,
		arg.TextDensity,
		arg.ContentText,
		arg.CleanedText,
		arg.SectionsJson,
		arg.ChunksJson,
		arg.TablesJson,
		arg.RawMetadataJson,
	)
	var i ParseRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.ParserName,
		&i.ParserVersion,
		&i.RequiresOcr,
		&i.ErrorMessage,
		&i.PageCount,
		&i.TextDensity,
		&i.ContentText,
		&i.CleanedText,
		&i.SectionsJson,
		&i.ChunksJson,
		&i.TablesJson,
		&i.RawMetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :one
INSERT INTO plans (
    signal_id,
    document_id,
    symbol,
    strategy,
    trade_date,
    direction,
    entry_price,
    stop_loss,
    take_profit,
    invalidation_price,
    position_pct,
    status,
    rationale,
    config_version,
    rule_version,
    market_snapshot_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, signal_id, document_id, symbol, strategy, trade_date, direction, entry_price, stop_loss, take_profit, invalidation_price, position_pct, status, rationale, config_version, rule_version, market_snapshot_id, approved_by, approved_at, created_at, updated_at
`

type InsertPlanParams struct {
	SignalID          int64       `json:"signal_id"`
	DocumentID        int64       `json:"document_id"`
	Symbol            string      `json:"symbol"`
	Strategy          string      `json:"strategy"`
	TradeDate         pgtype.Date `json:"trade_date"`
	Direction         string      `json:"direction"`
	EntryPrice        float64     `json:"entry_price"`
	StopLoss          float64     `json:"stop_loss"`
	TakeProfit        float64     `json:"take_profit"`
	InvalidationPrice float64     `json:"invalidation_price"`
	PositionPct       float64     `json:"position_pct"`
	Status            string      `json:"status"`
	Rationale         string      `json:"rationale"`
	ConfigVersion     int64       `json:"config_version"`
	RuleVersion       string      `json:"rule_version"`
	MarketSnapshotID  int64       `json:"market_snapshot_id"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.SignalID,
		arg.DocumentID,
		arg.Symbol,
		arg.Strategy,
		arg.TradeDate,
		arg.Direction,
		arg.EntryPrice,
		arg.StopLoss,
		arg.TakeProfit,
		arg.InvalidationPrice,
		arg.PositionPct,
		arg.Status,
		arg.Rationale,
		arg.ConfigVersion,
		arg.RuleVersion,
		arg.MarketSnapshotID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SignalID,
		&i.DocumentID,
		&i.Symbol,
		&i.Strategy,
		&i.TradeDate,
		&i.Direction,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.InvalidationPrice,
		&i.PositionPct,
		&i.Status,
		&i.Rationale,
		&i.ConfigVersion,
		&i.RuleVersion,
		&i.MarketSnapshotID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSignal = `-- name: InsertSignal :one
INSERT INTO signals (
    document_id,
    parse_run_id,
    expert_name,
    expert_org,
    symbol,
    asset_type,
    market,
    sentiment,
    thesis,
    evidence_json,
    risks_json,
    confidence,
    config_version,
    rule_version,
    signal_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, document_id, parse_run_id, expert_name, expert_org, symbol, asset_type, market, sentiment, thesis, evidence_json, risks_json, confidence, config_version, rule_version, signal_date, created_at
`

type InsertSignalParams struct {
	DocumentID    int64       `json:"document_id"`
	ParseRunID    int64       `json:"parse_run_id"`
	ExpertName    string      `json:"expert_name"`
	ExpertOrg     string      `json:"expert_org"`
	Symbol        string      `json:"symbol"`
	AssetType     string      `json:"asset_type"`
	Market        string      `json:"market"`
	Sentiment     string      `json:"sentiment"`
	Thesis        string      `json:"thesis"`
	EvidenceJson  []byte      `json:"evidence_json"`
	RisksJson     []byte      `json:"risks_json"`
	Confidence    float64     `json:"confidence"`
	ConfigVersion int64       `json:"config_version"`
	RuleVersion   string      `json:"rule_version"`
	SignalDate    pgtype.Date `json:"signal_date"`
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, insertSignal,
		arg.DocumentID,
		arg.ParseRunID,
		arg.ExpertName,
		arg.ExpertOrg,
		arg.Symbol,
		arg.AssetType,
		arg.Market,
		arg.Sentiment,
		arg.Thesis,
		arg.EvidenceJson,
		arg.RisksJson,
		arg.Confidence,
		arg.ConfigVersion,
		arg.RuleVersion,
		arg.SignalDate,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParseRunID,
		&i.ExpertName,
		&i.ExpertOrg,
		&i.Symbol,
		&i.AssetType,
		&i.Market,
		&i.Sentiment,
		&i.Thesis,
		&i.EvidenceJson,
		&i.RisksJson,
		&i.Confidence,
		&i.ConfigVersion,
		&i.RuleVersion,
		&i.SignalDate,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedPlansForTradeDateWithoutEvaluation = `-- name: ListApprovedPlansForTradeDateWithoutEvaluation :many
SELECT p.id, p.signal_id, p.document_id, p.symbol, p.strategy, p.trade_date, p.direction, p.entry_price, p.stop_loss, p.take_profit, p.invalidation_price, p.position_pct, p.status, p.rationale, p.config_version, p.rule_version, p.market_snapshot_id, p.approved_by, p.approved_at, p.created_at, p.updated_at
FROM plans p
LEFT JOIN evaluations e ON e.plan_id = p.id
WHERE p.status = 'APPROVED'
  AND p.trade_date = $1
  AND e.id IS NULL
ORDER BY p.created_at ASC
`

func (q *Queries) ListApprovedPlansForTradeDateWithoutEvaluation(ctx context.Context, tradeDate pgtype.Date) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listApprovedPlansForTradeDateWithoutEvaluation, tradeDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.SignalID,
			&i.DocumentID,
			&i.Symbol,
			&i.Strategy,
			&i.TradeDate,
			&i.Direction,
			&i.EntryPrice,
			&i.StopLoss,
			&i.TakeProfit,
			&i.InvalidationPrice,
			&i.PositionPct,
			&i.Status,
			&i.Rationale,
			&i.ConfigVersion,
			&i.RuleVersion,
			&i.MarketSnapshotID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, object_key, status, config_version, created_at, updated_at
FROM documents
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListDocuments(ctx context.Context, limit int32) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceName,
			&i.Author,
			&i.Institution,
			&i.Title,
			&i.FileName,
			&i.Extension,
			&i.ContentType,
			&i.Sha256,
			&i.ObjectKey,
			&i.Status,
			&i.ConfigVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByStatus = `-- name: ListDocumentsByStatus :many
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, object_key, status, config_version, created_at, updated_at
FROM documents
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListDocumentsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListDocumentsByStatus(ctx context.Context, arg ListDocumentsByStatusParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceName,
			&i.Author,
			&i.Institution,
			&i.Title,
			&i.FileName,
			&i.Extension,
			&i.ContentType,
			&i.Sha256,
			&i.ObjectKey,
			&i.Status,
			&i.ConfigVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluations = `-- name: ListEvaluations :many
SELECT id, plan_id, trade_date, status, entry_price, exit_price, close_price, pnl_pct, mfe_pct, mae_pct, benchmark_return_pct, excess_return_pct, reason, data_quality_flag, config_version, created_at
FROM evaluations
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListEvaluations(ctx context.Context, limit int32) ([]Evaluation, error) {
	rows, err := q.db.Query(ctx, listEvaluations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evaluation
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.TradeDate,
			&i.Status,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.ClosePrice,
			&i.PnlPct,
			&i.MfePct,
			&i.MaePct,
			&i.BenchmarkReturnPct,
			&i.ExcessReturnPct,
			&i.Reason,
			&i.DataQualityFlag,
			&i.ConfigVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, signal_id, document_id, symbol, strategy, trade_date, direction, entry_price, stop_loss, take_profit, invalidation_price, position_pct, status, rationale, config_version, rule_version, market_snapshot_id, approved_by, approved_at, created_at, updated_at
FROM plans
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListPlans(ctx context.Context, limit int32) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.SignalID,
			&i.DocumentID,
			&i.Symbol,
			&i.Strategy,
			&i.TradeDate,
			&i.Direction,
			&i.EntryPrice,
			&i.StopLoss,
			&i.TakeProfit,
			&i.InvalidationPrice,
			&i.PositionPct,
			&i.Status,
			&i.Rationale,
			&i.ConfigVersion,
			&i.RuleVersion,
			&i.MarketSnapshotID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalsByDocumentID = `-- name: ListSignalsByDocumentID :many
SELECT id, document_id, parse_run_id, expert_name, expert_org, symbol, asset_type, market, sentiment, thesis, evidence_json, risks_json, confidence, config_version, rule_version, signal_date, created_at
FROM signals
WHERE document_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSignalsByDocumentID(ctx context.Context, documentID int64) ([]Signal, error) {
	rows, err := q.db.Query(ctx, listSignalsByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signal
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParseRunID,
			&i.ExpertName,
			&i.ExpertOrg,
			&i.Symbol,
			&i.AssetType,
			&i.Market,
			&i.Sentiment,
			&i.Thesis,
			&i.EvidenceJson,
			&i.RisksJson,
			&i.Confidence,
			&i.ConfigVersion,
			&i.RuleVersion,
			&i.SignalDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.Status)
	return err
}
