// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deletePlansByDocumentID = `-- name: DeletePlansByDocumentID :exec
DELETE FROM trade_candidate_plans
WHERE document_id = ?
`

func (q *Queries) DeletePlansByDocumentID(ctx context.Context, documentID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlansByDocumentID, documentID)
	return err
}

const getConfigSnapshotByID = `-- name: GetConfigSnapshotByID :one
SELECT id, config_version, source, sha256, raw_json, created_at
FROM config_snapshots
WHERE id = ?
`

func (q *Queries) GetConfigSnapshotByID(ctx context.Context, id int64) (ConfigSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getConfigSnapshotByID, id)
	var i ConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.ConfigVersion,
		&i.Source,
		&i.Sha256,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, status, config_version, raw_content, created_at, updated_at
FROM documents
WHERE id = ?
`

func (q *Queries) GetDocumentByID(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceName,
		&i.Author,
		&i.Institution,
		&i.Title,
		&i.FileName,
		&i.Extension,
		&i.ContentType,
		&i.Sha256,
		&i.Status,
		&i.ConfigVersion,
		&i.RawContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySHA = `-- name: GetDocumentBySHA :one
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, status, config_version, raw_content, created_at, updated_at
FROM documents
WHERE sha256 = ?
`

func (q *Queries) GetDocumentBySHA(ctx context.Context, sha256 string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySHA, sha256)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceName,
		&i.Author,
		&i.Institution,
		&i.Title,
		&i.FileName,
		&i.Extension,
		&i.ContentType,
		&i.Sha256,
		&i.Status,
		&i.ConfigVersion,
		&i.RawContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestParseRunByDocumentID = `-- name: GetLatestParseRunByDocumentID :one
SELECT id, document_id, status, parser_name, parser_version, error_message, page_count, content_text, cleaned_text, chunks_json, raw_metadata_json, created_at, updated_at
FROM parse_runs
WHERE document_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestParseRunByDocumentID(ctx context.Context, documentID int64) (ParseRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestParseRunByDocumentID, documentID)
	var i ParseRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.ParserName,
		&i.ParserVersion,
		&i.ErrorMessage,
		&i.PageCount,
		&i.ContentText,
		&i.CleanedText,
		&i.ChunksJson,
		&i.RawMetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParseRunByID = `-- name: GetParseRunByID :one
SELECT id, document_id, status, parser_name, parser_version, error_message, page_count, content_text, cleaned_text, chunks_json, raw_metadata_json, created_at, updated_at
FROM parse_runs
WHERE id = ?
`

func (q *Queries) GetParseRunByID(ctx context.Context, id int64) (ParseRun, error) {
	row := q.db.QueryRowContext(ctx, getParseRunByID, id)
	var i ParseRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.ParserName,
		&i.ParserVersion,
		&i.ErrorMessage,
		&i.PageCount,
		&i.ContentText,
		&i.CleanedText,
		&i.ChunksJson,
		&i.RawMetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, document_id, parse_run_id, analyst, institution, symbol, asset_type, market, strategy, direction, trade_date, reference_price, entry_price, stop_loss, take_profit, position_pct, confidence, status, thesis, risks_json, evidence_json, pricing_note, config_version, rule_version, created_at, updated_at
FROM trade_candidate_plans
WHERE id = ?
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (TradeCandidatePlan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByID, id)
	var i TradeCandidatePlan
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParseRunID,
		&i.Analyst,
		&i.Institution,
		&i.Symbol,
		&i.AssetType,
		&i.Market,
		&i.Strategy,
		&i.Direction,
		&i.TradeDate,
		&i.ReferencePrice,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.PositionPct,
		&i.Confidence,
		&i.Status,
		&i.Thesis,
		&i.RisksJson,
		&i.EvidenceJson,
		&i.PricingNote,
		&i.ConfigVersion,
		&i.RuleVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfigSnapshot = `-- name: InsertConfigSnapshot :execresult
INSERT INTO config_snapshots (
    config_version,
    source,
    sha256,
    raw_json
) VALUES (
    ?, ?, ?, ?
)
`

type InsertConfigSnapshotParams struct {
	ConfigVersion int64           `json:"config_version"`
	Source        string          `json:"source"`
	Sha256        string          `json:"sha256"`
	RawJson       json.RawMessage `json:"raw_json"`
}

func (q *Queries) InsertConfigSnapshot(ctx context.Context, arg InsertConfigSnapshotParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertConfigSnapshot,
		arg.ConfigVersion,
		arg.Source,
		arg.Sha256,
		arg.RawJson,
	)
}

const insertDocument = `-- name: InsertDocument :execresult
INSERT INTO documents (
    source_type,
    source_name,
    author,
    institution,
    title,
    file_name,
    extension,
    content_type,
    sha256,
    status,
    config_version,
    raw_content
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertDocumentParams struct {
	SourceType    string `json:"source_type"`
	SourceName    string `json:"source_name"`
	Author        string `json:"author"`
	Institution   string `json:"institution"`
	Title         string `json:"title"`
	FileName      string `json:"file_name"`
	Extension     string `json:"extension"`
	ContentType   string `json:"content_type"`
	Sha256        string `json:"sha256"`
	Status        string `json:"status"`
	ConfigVersion int64  `json:"config_version"`
	RawContent    []byte `json:"raw_content"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertDocument,
		arg.SourceType,
		arg.SourceName,
		arg.Author,
		arg.Institution,
		arg.Title,
		arg.FileName,
		arg.Extension,
		arg.ContentType,
		arg.Sha256,
		arg.Status,
		arg.ConfigVersion,
		arg.RawContent,
	)
}

const insertParseRun = `-- name: InsertParseRun :execresult
INSERT INTO parse_runs (
    document_id,
    status,
    parser_name,
    parser_version,
    error_message,
    page_count,
    content_text,
    cleaned_text,
    chunks_json,
    raw_metadata_json
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertParseRunParams struct {
	DocumentID      int64           `json:"document_id"`
	Status          string          `json:"status"`
	ParserName      string          `json:"parser_name"`
	ParserVersion   string          `json:"parser_version"`
	ErrorMessage    string          `json:"error_message"`
	PageCount       int32           `json:"page_count"`
	ContentText     string          `json:"content_text"`
	CleanedText     string          `json:"cleaned_text"`
	ChunksJson      json.RawMessage `json:"chunks_json"`
	RawMetadataJson json.RawMessage `json:"raw_metadata_json"`
}

func (q *Queries) InsertParseRun(ctx context.Context, arg InsertParseRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertParseRun,
		arg.DocumentID,
		arg.Status,
		arg.ParserName,
		arg.ParserVersion,
		arg.ErrorMessage,
		arg.PageCount,
		arg.ContentText,
		arg.CleanedText,
		arg.ChunksJson,
		arg.RawMetadataJson,
	)
}

const insertPlan = `-- name: InsertPlan :execresult
INSERT INTO trade_candidate_plans (
    document_id,
    parse_run_id,
    analyst,
    institution,
    symbol,
    asset_type,
    market,
    strategy,
    direction,
    trade_date,
    reference_price,
    entry_price,
    stop_loss,
    take_profit,
    position_pct,
    confidence,
    status,
    thesis,
    risks_json,
    evidence_json,
    pricing_note,
    config_version,
    rule_version
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertPlanParams struct {
	DocumentID     int64           `json:"document_id"`
	ParseRunID     int64           `json:"parse_run_id"`
	Analyst        string          `json:"analyst"`
	Institution    string          `json:"institution"`
	Symbol         string          `json:"symbol"`
	AssetType      string          `json:"asset_type"`
	Market         string          `json:"market"`
	Strategy       string          `json:"strategy"`
	Direction      string          `json:"direction"`
	TradeDate      time.Time       `json:"trade_date"`
	ReferencePrice float64         `json:"reference_price"`
	EntryPrice     float64         `json:"entry_price"`
	StopLoss       float64         `json:"stop_loss"`
	TakeProfit     float64         `json:"take_profit"`
	PositionPct    float64         `json:"position_pct"`
	Confidence     float64         `json:"confidence"`
	Status         string          `json:"status"`
	Thesis         string          `json:"thesis"`
	RisksJson      json.RawMessage `json:"risks_json"`
	EvidenceJson   json.RawMessage `json:"evidence_json"`
	PricingNote    string          `json:"pricing_note"`
	ConfigVersion  int64           `json:"config_version"`
	RuleVersion    string          `json:"rule_version"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPlan,
		arg.DocumentID,
		arg.ParseRunID,
		arg.Analyst,
		arg.Institution,
		arg.Symbol,
		arg.AssetType,
		arg.Market,
		arg.Strategy,
		arg.Direction,
		arg.TradeDate,
		arg.ReferencePrice,
		arg.EntryPrice,
		arg.StopLoss,
		arg.TakeProfit,
		arg.PositionPct,
		arg.Confidence,
		arg.Status,
		arg.Thesis,
		arg.RisksJson,
		arg.EvidenceJson,
		arg.PricingNote,
		arg.ConfigVersion,
		arg.RuleVersion,
	)
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, source_type, source_name, author, institution, title, file_name, extension, content_type, sha256, status, config_version, raw_content, created_at, updated_at
FROM documents
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListDocuments(ctx context.Context, limit int32) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceName,
			&i.Author,
			&i.Institution,
			&i.Title,
			&i.FileName,
			&i.Extension,
			&i.ContentType,
			&i.Sha256,
			&i.Status,
			&i.ConfigVersion,
			&i.RawContent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, document_id, parse_run_id, analyst, institution, symbol, asset_type, market, strategy, direction, trade_date, reference_price, entry_price, stop_loss, take_profit, position_pct, confidence, status, thesis, risks_json, evidence_json, pricing_note, config_version, rule_version, created_at, updated_at
FROM trade_candidate_plans
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListPlans(ctx context.Context, limit int32) ([]TradeCandidatePlan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeCandidatePlan
	for rows.Next() {
		var i TradeCandidatePlan
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParseRunID,
			&i.Analyst,
			&i.Institution,
			&i.Symbol,
			&i.AssetType,
			&i.Market,
			&i.Strategy,
			&i.Direction,
			&i.TradeDate,
			&i.ReferencePrice,
			&i.EntryPrice,
			&i.StopLoss,
			&i.TakeProfit,
			&i.PositionPct,
			&i.Confidence,
			&i.Status,
			&i.Thesis,
			&i.RisksJson,
			&i.EvidenceJson,
			&i.PricingNote,
			&i.ConfigVersion,
			&i.RuleVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByDocumentID = `-- name: ListPlansByDocumentID :many
SELECT id, document_id, parse_run_id, analyst, institution, symbol, asset_type, market, strategy, direction, trade_date, reference_price, entry_price, stop_loss, take_profit, position_pct, confidence, status, thesis, risks_json, evidence_json, pricing_note, config_version, rule_version, created_at, updated_at
FROM trade_candidate_plans
WHERE document_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListPlansByDocumentID(ctx context.Context, documentID int64) ([]TradeCandidatePlan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeCandidatePlan
	for rows.Next() {
		var i TradeCandidatePlan
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParseRunID,
			&i.Analyst,
			&i.Institution,
			&i.Symbol,
			&i.AssetType,
			&i.Market,
			&i.Strategy,
			&i.Direction,
			&i.TradeDate,
			&i.ReferencePrice,
			&i.EntryPrice,
			&i.StopLoss,
			&i.TakeProfit,
			&i.PositionPct,
			&i.Confidence,
			&i.Status,
			&i.Thesis,
			&i.RisksJson,
			&i.EvidenceJson,
			&i.PricingNote,
			&i.ConfigVersion,
			&i.RuleVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDocumentStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentStatus, arg.Status, arg.ID)
	return err
}
