// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"encoding/json"
	"time"
)

type ConfigSnapshot struct {
	ID            int64           `json:"id"`
	ConfigVersion int64           `json:"config_version"`
	Source        string          `json:"source"`
	Sha256        string          `json:"sha256"`
	RawJson       json.RawMessage `json:"raw_json"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Document struct {
	ID            int64     `json:"id"`
	SourceType    string    `json:"source_type"`
	SourceName    string    `json:"source_name"`
	Author        string    `json:"author"`
	Institution   string    `json:"institution"`
	Title         string    `json:"title"`
	FileName      string    `json:"file_name"`
	Extension     string    `json:"extension"`
	ContentType   string    `json:"content_type"`
	Sha256        string    `json:"sha256"`
	Status        string    `json:"status"`
	ConfigVersion int64     `json:"config_version"`
	RawContent    []byte    `json:"raw_content"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ParseRun struct {
	ID              int64           `json:"id"`
	DocumentID      int64           `json:"document_id"`
	Status          string          `json:"status"`
	ParserName      string          `json:"parser_name"`
	ParserVersion   string          `json:"parser_version"`
	ErrorMessage    string          `json:"error_message"`
	PageCount       int32           `json:"page_count"`
	ContentText     string          `json:"content_text"`
	CleanedText     string          `json:"cleaned_text"`
	ChunksJson      json.RawMessage `json:"chunks_json"`
	RawMetadataJson json.RawMessage `json:"raw_metadata_json"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type TradeCandidatePlan struct {
	ID             int64           `json:"id"`
	DocumentID     int64           `json:"document_id"`
	ParseRunID     int64           `json:"parse_run_id"`
	Analyst        string          `json:"analyst"`
	Institution    string          `json:"institution"`
	Symbol         string          `json:"symbol"`
	AssetType      string          `json:"asset_type"`
	Market         string          `json:"market"`
	Strategy       string          `json:"strategy"`
	Direction      string          `json:"direction"`
	TradeDate      time.Time       `json:"trade_date"`
	ReferencePrice float64         `json:"reference_price"`
	EntryPrice     float64         `json:"entry_price"`
	StopLoss       float64         `json:"stop_loss"`
	TakeProfit     float64         `json:"take_profit"`
	PositionPct    float64         `json:"position_pct"`
	Confidence     float64         `json:"confidence"`
	Status         string          `json:"status"`
	Thesis         string          `json:"thesis"`
	RisksJson      json.RawMessage `json:"risks_json"`
	EvidenceJson   json.RawMessage `json:"evidence_json"`
	PricingNote    string          `json:"pricing_note"`
	ConfigVersion  int64           `json:"config_version"`
	RuleVersion    string          `json:"rule_version"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
