// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApprovePlan(ctx context.Context, arg ApprovePlanParams) (Plan, error)
	GetDocumentByID(ctx context.Context, id int64) (Document, error)
	GetDocumentBySHA(ctx context.Context, sha256 string) (Document, error)
	GetLatestParseRunByDocumentID(ctx context.Context, documentID int64) (ParseRun, error)
	GetMarketSnapshotBySymbolDate(ctx context.Context, arg GetMarketSnapshotBySymbolDateParams) (MarketSnapshot, error)
	GetPlanByID(ctx context.Context, id int64) (Plan, error)
	GetSignalByID(ctx context.Context, id int64) (Signal, error)
	InsertConfigSnapshot(ctx context.Context, arg InsertConfigSnapshotParams) (ConfigSnapshot, error)
	InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error)
	InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (Evaluation, error)
	InsertMarketSnapshot(ctx context.Context, arg InsertMarketSnapshotParams) (MarketSnapshot, error)
	InsertParseRun(ctx context.Context, arg InsertParseRunParams) (ParseRun, error)
	InsertPlan(ctx context.Context, arg InsertPlanParams) (Plan, error)
	InsertSignal(ctx context.Context, arg InsertSignalParams) (Signal, error)
	ListApprovedPlansForTradeDateWithoutEvaluation(ctx context.Context, tradeDate pgtype.Date) ([]Plan, error)
	ListDocuments(ctx context.Context, limit int32) ([]Document, error)
	ListDocumentsByStatus(ctx context.Context, arg ListDocumentsByStatusParams) ([]Document, error)
	ListEvaluations(ctx context.Context, limit int32) ([]Evaluation, error)
	ListPlans(ctx context.Context, limit int32) ([]Plan, error)
	ListSignalsByDocumentID(ctx context.Context, documentID int64) ([]Signal, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error
}

var _ Querier = (*Queries)(nil)
