// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeletePlansByDocumentID(ctx context.Context, documentID int64) error
	GetConfigSnapshotByID(ctx context.Context, id int64) (ConfigSnapshot, error)
	GetDocumentByID(ctx context.Context, id int64) (Document, error)
	GetDocumentBySHA(ctx context.Context, sha256 string) (Document, error)
	GetLatestParseRunByDocumentID(ctx context.Context, documentID int64) (ParseRun, error)
	GetParseRunByID(ctx context.Context, id int64) (ParseRun, error)
	GetPlanByID(ctx context.Context, id int64) (TradeCandidatePlan, error)
	InsertConfigSnapshot(ctx context.Context, arg InsertConfigSnapshotParams) (sql.Result, error)
	InsertDocument(ctx context.Context, arg InsertDocumentParams) (sql.Result, error)
	InsertParseRun(ctx context.Context, arg InsertParseRunParams) (sql.Result, error)
	InsertPlan(ctx context.Context, arg InsertPlanParams) (sql.Result, error)
	ListDocuments(ctx context.Context, limit int32) ([]Document, error)
	ListPlans(ctx context.Context, limit int32) ([]TradeCandidatePlan, error)
	ListPlansByDocumentID(ctx context.Context, documentID int64) ([]TradeCandidatePlan, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error
}

var _ Querier = (*Queries)(nil)
